<?php

/**
 * Admin_M_Sucursal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Admin_M_Sucursal.php 97 2012-08-01 21:57:04Z mprado $
 */
class Admin_M_Sucursal extends BaseAdmin_M_Sucursal
{
    public function setUp() 
    {

	$this->hasOne('Admin', array(
                'local' => 'admin_id',
                'foreign' => 'id',
		'onDelete' => 'CASCADE'
            ));
        
        $this->hasOne('sucursal', array(
                'local' => 'sucursal_id',
                'foreign' => 'id',
		'onDelete' => 'CASCADE'
            ));

    }

    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this));
        $query->where("1 = 1");
        return $query;
    }
}