<?php

/**
 * Admin_Puesto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Admin_Puesto.php 97 2012-08-01 21:57:04Z mprado $
 */
class Admin_Puesto extends BaseAdmin_Puesto
{
    public function setUp() {
		
	$this->actAs('Timestampable');
		
	$this->hasMany('Admin as Many_Admin', array(
                'refClass' => 'Admin_M_Admin_Puesto',
                'local' => 'admin_puesto_id',
                'foreign' => 'admin_id'
        ));
    }

    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this));
        $query->where("1 = 1");
        return $query;
    }
}