<?php

/**
 * Admin_M_Grupo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Admin_M_Grupo.php 97 2012-08-01 21:57:04Z mprado $
 */
class Admin_M_Grupo extends BaseAdmin_M_Grupo
{
    public function setUp() {
			
	$this->hasOne('Admin', array(
                'local' => 'admin_id',
                'foreign' => 'id',
		'onDelete' => 'CASCADE'
                ));
        
        $this->hasOne('Grupo', array(
                'local' => 'grupo_id',
                'foreign' => 'id',
                'onDelete' => 'CASCADE'
                ));		
    }

    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this));
        $query->where("1 = 1");
        return $query;
    }
}