<?php

/**
 * Admin_Departamento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Admin_Departamento.php 97 2012-08-01 21:57:04Z mprado $
 */
class Admin_Departamento extends BaseAdmin_Departamento
{
    public function setUp() {
		
	$this->actAs('Timestampable');
		
	$this->hasMany('Admin as Many_Admin', array(
            'refClass' => 'Admin_M_Admin_Departamento',
            'local' => 'admin_departamento_id',
            'foreign' => 'admin_id'
            ));
    }

    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this));
        $query->where("1 = 1");
        return $query;
    }
}