<?php

/**
 * Auto_Version
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Auto_Version.php 174 2012-08-30 01:07:28Z agusquiroga $
 */
class Auto_Version extends BaseAuto_Version
{
    public function setUp() {
		
        $this->actAs('Timestampable');
        $this->actAs('SoftDelete');

        $this->hasOne('Auto_Modelo', array(
                'local' => 'auto_modelo_id',
                'foreign' => 'id'
                ));
		
		
	$this->hasMany('Unidad', array(
                'local' => 'id',
                'foreign' => 'auto_version_id',
                ));
		
        $this->hasMany('Usado', array(
                'local' => 'id',
                'foreign' => 'auto_version_id',
                ));
		
       $this->hasMany('vin_version', array(
                'local' => 'id',
                'foreign' => 'vin_version_id',
                ));
	
    }
	
    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this) . ' V ');
        $query->leftJoin('V.Auto_Modelo AM');
        $query->leftJoin('AM.Auto_Marca AMA');
        $query->where("1 = 1");
        return $query;
    }
	
	
    public function get_versiones_honda($activas = TRUE)
    {
        $query = Doctrine_Query::create();
        $query->select('V.id, V.id AS version_id,AM.auto_modelo_field_desc, V.auto_version_field_desc');
        $query->from(get_class($this) . ' V ');

        $query->leftJoin('V.Auto_Modelo AM');
        if($activas)
        {
            $query->leftJoin('V.Unidad U');
        }

        $query->Where('auto_marca_id = ?', 100); //marca honda
        if($activas)
        {
            $query->addWhere('U.id != ?', FALSE); //modelo honda
        }

        $query->groupBy('V.id'); //modelo

        $query->orderBy('auto_modelo_field_desc'); //modelo
        $query->addOrderBy('auto_version_field_desc'); //modelo

        return $query;
    }
}