<?php

/**
 * Auto_Marca
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Auto_Marca.php 97 2012-08-01 21:57:04Z mprado $
 */
class Auto_Marca extends BaseAuto_Marca
{
    public function setUp() {
		
        $this->actAs('Timestampable');
        $this->actAs('SoftDelete');

        $this->hasMany('Auto_Modelo', array(
            'local' => 'id',
            'foreign' => 'auto_modelo_id',
            ));
    }
	
    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this));
        $query->where("1 = 1");
        return $query;
    }
}