<?php

/**
 * Auto_Transmision
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Auto_Transmision.php 97 2012-08-01 21:57:04Z mprado $
 */
class Auto_Transmision extends BaseAuto_Transmision
{
    public function setUp() 
    {
		
        $this->actAs('Timestampable');
        $this->actAs('SoftDelete');


        $this->hasMany('Vin_Puerta_Transmision', array(
            'local' => 'id',
            'foreign' => 'auto_transmision_id',
            ));

        $this->hasMany('Unidad', array(
            'local' => 'id',
            'foreign' => 'auto_transmision_id',
            ));
    }

    public function get_all() 
    {

        $query = Doctrine_Query::create();
        $query->from(get_class($this));
        $query->where("1 = 1");
        return $query;
    }

}