<?php

/**
 * Auto_Combustible
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Auto_Combustible.php 97 2012-08-01 21:57:04Z mprado $
 */
class Auto_Combustible extends BaseAuto_Combustible
{
    public function setUp() {
		
	$this->actAs('Timestampable');
	$this->actAs('SoftDelete');
		
		
	$this->hasMany('Unidad', array(
            'local' => 'id',
            'foreign' => 'auto_combustible_id',
            ));
    }

    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this));
        $query->where("1 = 1");
        return $query;
    }
}