<?php

/**
 * Backend_Estado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Backend_Estado.php 97 2012-08-01 21:57:04Z mprado $
 */
class Backend_Estado extends BaseBackend_Estado
{
    public function setUp() {
		
        $this->actAs('Timestampable');
        $this->actAs('SoftDelete');

        $this->hasMany('Noticia', array(
                'local' => 'backend_estado_id',
                'foreign' => 'id',
                ));

        $this->hasMany('Sucursal', array(
                'local' => 'backend_estado_id',
                'foreign' => 'id',
                ));
        
        $this->hasMany('Sucursal_Servicio', array(
                'local' => 'backend_estado_id',
                'foreign' => 'id',
                ));

        $this->hasMany('Sucursal as Reporte_Usados_Sucursal', array(
                'local' => 'sucursal_field_reporte_usados',
                'foreign' => 'id',
                ));
        
        $this->hasMany('Usado', array(
                'local' => 'backend_estado_id',
                'foreign' => 'id',
                ));
        
        $this->hasMany('Trafico_Pilot_Legend', array(
                'local' => 'id',
                'foreign' => 'backend_estado_id',
                ));

        $this->hasMany('Reclamo_Garantia_Version', array(
                'local' => 'id',
                'foreign' => 'backend_estado_id',
                ));
    }

    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this));
        $query->where("1 = 1");
        return $query;
    }
}