<?php

/**
 * Boutique_Pedido
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Boutique_Pedido.php 260 2012-10-01 18:30:28Z mprado $
 */
class Boutique_Pedido extends BaseBoutique_Pedido
{
    public function setUp() {

	$this->actAs('Timestampable');

	$this->hasOne('Admin', array(
            'local' => 'admin_id',
            'foreign' => 'id',
            'onDelete' => 'CASCADE'
            ));

	$this->hasOne('Sucursal', array(
            'local' => 'sucursal_id',
            'foreign' => 'id'
            ));

	$this->hasOne('Boutique_Pedido_Estado', array(
            'local' => 'boutique_pedido_estado',
            'foreign' => 'id',
            ));

	$this->hasMany('Boutique_Pedido_Detalle', array(
            'local' => 'id',
            'foreign' => 'boutique_pedido_id',
            'onDelete' => 'CASCADE'
            ));
    }

    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this) .' BOUTIQUE_PEDIDO ');

        //Joins Estado
        $query->leftJoin("BOUTIQUE_PEDIDO.Admin ADMIN ");

        //Sucursal
        $query->leftjoin("BOUTIQUE_PEDIDO.Sucursal SUCURSAL");

        //Joins Estado
        $query->leftJoin("BOUTIQUE_PEDIDO.Boutique_Pedido_Estado BOUTIQUE_PEDIDO_ESTADO ");
        
        //Joins Detalle
        $query->leftJoin("BOUTIQUE_PEDIDO.Boutique_Pedido_Detalle BOUTIQUE_PEDIDO_DETALLE ");
        
        //Joins Productos
        $query->leftJoin("BOUTIQUE_PEDIDO_DETALLE.Boutique_Producto BOUTIQUE_PRODUCTO");


        return $query;
    }
}