<?php

/**
 * Boutique_Pedido_Detalle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Boutique_Pedido_Detalle.php 242 2012-09-19 21:47:35Z mprado $
 */
class Boutique_Pedido_Detalle extends BaseBoutique_Pedido_Detalle
{
    public function setUp() 
    {

	$this->actAs('Timestampable');

	//Admin (Proovedor)
	$this->hasOne('Admin as Proovedor' , array(
            'local'   => 'proovedor_id',
            'foreign' => 'id'
            ));
        
	//Producto
	$this->hasOne('Boutique_Producto' , array(
            'local'   => 'boutique_producto_id',
            'foreign' => 'id'
            ));

	//Categoria
	$this->hasMany('Boutique_Categoria as Many_Boutique_Categoria', array(
            'refClass' => 'Boutique_Producto_M_Categoria',
            'local'    => 'boutique_producto_id',
            'foreign'  => 'Boutique_Categoria_id',
            ));

	//Color
	$this->hasOne('Boutique_Color' , array(
            'local'   => 'boutique_color',
            'foreign' => 'id'
            ));

	//Talle
	$this->hasOne('Boutique_Talle' , array(
            'local'   => 'boutique_talle',
            'foreign' => 'id'
            ));
    }

    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this) .' BOUTIQUE_PEDIDO_DETALLE ');

        //Joins Producto
        $query->leftJoin("BOUTIQUE_PEDIDO_DETALLE.Boutique_Producto BOUTIQUE_PRODUCTO ");

        //Joins Disponibildiad
        $query->leftJoin("BOUTIQUE_PRODUCTO.Boutique_Disponibilidad BOUTIQUE_DISPONIBILIDAD ");

        //Join Categoria
        $query->leftJoin("BOUTIQUE_PRODUCTO.Many_Boutique_Categoria MBCa");

        //Join Color
        $query->leftJoin("BOUTIQUE_PEDIDO_DETALLE.Boutique_Color BCo");

        //Join Talle
        $query->leftJoin("BOUTIQUE_PEDIDO_DETALLE.Boutique_Talle BT");
        
        //Join Admn
        $query->leftJoin("BOUTIQUE_PEDIDO_DETALLE.Proovedor BOUTIQUE_PROOVEDOR");
        
        //Join Sucursal
        $query->leftJoin("BOUTIQUE_PROOVEDOR.Sucursal SUCURSAL");
        

        return $query;
    }

}