<?php

/**
 * Boutique
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Boutique.php 98 2012-08-02 19:31:55Z mprado $
 */
class Boutique extends BaseBoutique
{
    public function setUp() {

	$this->actAs('Timestampable');	

	//Estado
	$this->hasOne('Boutique_Producto_Estado' , array(
            'local'   => 'boutique_producto_estado_id',
            'foreign' => 'id'
            ));

        //Disponibilidad
	$this->hasOne('Boutique_Disponibilidad' , array(
            'local'   => 'boutique_disponibilidad_id',
            'foreign' => 'id'
            ));

	//Categoria
	$this->hasMany('Boutique_Categoria as Many_Boutique_Categoria', array(
            'refClass' => 'Boutique_Producto_M_Categoria',
            'local'    => 'Boutique_Producto_id',
            'foreign'  => 'Boutique_Categoria_id',
            ));

	//Color
	$this->hasMany('Boutique_Color as Many_Boutique_Color', array(
            'refClass' => 'Boutique_Producto_M_Color',
            'local'    => 'Boutique_Producto_id',
            'foreign'  => 'Boutique_Color_id',
            ));

	//Talle
	$this->hasMany('Boutique_Talle as Many_Boutique_Talle', array(
            'refClass' => 'Boutique_Producto_M_Talle',
            'local'    => 'Boutique_Producto_id',
            'foreign'  => 'Boutique_Talle_id',
            ));

	//Imagenes
	$this->hasMany('Boutique_Producto_Imagen', array(
            'local'   => 'id',
            'foreign' => 'boutique_producto_id'
            ));
    }

    public function get_all()
    {
        $from_table = get_class($this) . '_Producto';

        $query = Doctrine_Query::create();
        $query->from($from_table .' BOUTIQUE_PRODUCTO ');
        $query->where("1 = 1");

        //Joins Estado
        $query->leftJoin("BOUTIQUE_PRODUCTO.Boutique_Producto_Estado BOUTIQUE_PRODUCTO_ESTADO ");

        //Joins Disponibildiad
        $query->leftJoin("BOUTIQUE_PRODUCTO.Boutique_Disponibilidad BOUTIQUE_DISPONIBILIDAD ");

        //Join Categoria
        $query->leftJoin("BOUTIQUE_PRODUCTO.Many_Boutique_Categoria MBCa");

        //Join Color
        $query->leftJoin("BOUTIQUE_PRODUCTO.Many_Boutique_Color MBCo");

        //Join Talle
        $query->leftJoin("BOUTIQUE_PRODUCTO.Many_Boutique_Talle MBT");
        //Join Imagenes
        $query->leftJoin("BOUTIQUE_PRODUCTO.Boutique_Producto_Imagen BOUTIQUE_PRODUCTO_IMAGEN");

        //Return query con Join's
        return $query;
    }
}