<?php

/**
 * Boutique_Producto_Estado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Boutique_Producto_Estado.php 98 2012-08-02 19:31:55Z mprado $
 */
class Boutique_Producto_Estado extends BaseBoutique_Producto_Estado
{
    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this) .' BOUTIQUE_PRODUCTO_ESTADO ');
        $query->where("1 = 1");
        return $query;
    }
}