<?php

/**
 * Boutique_Producto_M_Color
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Boutique_Producto_M_Color.php 98 2012-08-02 19:31:55Z mprado $
 */
class Boutique_Producto_M_Color extends BaseBoutique_Producto_M_Color
{
    public function setUp() {		
		
	$this->hasOne('Boutique_Producto', array(
            'local' => 'boutique_producto_id',
            'foreign' => 'id',
            'onDelete' => 'CASCADE'
            ));
        
        $this->hasOne('Boutique_Color', array(
            'local' => 'boutique_color_id',
            'foreign' => 'id',
            'onDelete' => 'CASCADE'
            ));		
    }

    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this));
        $query->where("1 = 1");
        return $query;
    }
}