<?php

/**
 * Boutique_Producto_Imagen
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Boutique_Producto_Imagen.php 98 2012-08-02 19:31:55Z mprado $
 */
class Boutique_Producto_Imagen extends BaseBoutique_Producto_Imagen
{
    public function setUp() {
	
	$this->actAs('Timestampable');
	
	$this->hasOne('Boutique_Producto', array(
            'local' => 'boutique_producto_id',
            'foreign' => 'id'
            ));            
    }

    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this));
        $query->where("1 = 1");		
        return $query;
    }
}