<?php

/**
 * Ci_Sessions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Ci_Sessions.php 92 2012-08-01 16:51:56Z agusquiroga $
 */
class Ci_Sessions extends BaseCi_Sessions
{

}