<?php

/**
 * Ciudad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Ciudad.php 97 2012-08-01 21:57:04Z mprado $
 */
class Ciudad extends BaseCiudad
{
    public function setUp() {
		
	$this->actAs('Timestampable');		
		
	$this->hasMany('Sucursal', array(
            'local' => 'id',
            'foreign' => 'ciudad_id'
            ));
		
	$this->hasMany('Cliente_Sucursal', array(
            'local' => 'id',
            'foreign' => 'ciudad_id'
            ));
		
	$this->hasOne('Provincia', array(
            'local' => 'provincia_id',
            'foreign' => 'id'
            ));		
    }

    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this) .' C ');
        $query->where("1 = 1");

        $query->leftJoin('C.Provincia P ');
        return $query;
    }
}