<?php

/**
 * Cliente_Sucursal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Cliente_Sucursal.php 329 2012-10-18 05:00:55Z slopez $
 */
class Cliente_Sucursal extends BaseCliente_Sucursal
{
    public function setUp() {
		
	$this->actAs('Timestampable');
	$this->actAs('SoftDelete');
		
	$this->hasOne('Pais', array(
            'local' => 'pais_id',
            'foreign' => 'id'
            ));
		
	$this->hasOne('Provincia', array(
            'local' => 'provincia_id',
            'foreign' => 'id'
            ));
        
	$this->hasOne('Sexo', array(
            'local' => 'sexo_id',
            'foreign' => 'id'
            ));
        
	$this->hasOne('Tratamiento', array(
            'local' => 'tratamiento_id',
            'foreign' => 'id'
            ));
        
	$this->hasOne('Ciudad', array(
            'local' => 'ciudad_id',
            'foreign' => 'id'
            ));
	
        $this->hasOne('Sucursal', array(
            'local' => 'sucursal_id',
            'foreign' => 'id'
            ));
        
	$this->hasOne('Cliente', array(
            'local' => 'cliente_id',
            'foreign' => 'id'
            ));	
		
    }
	
    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this) .' CS ');
        $query->where("1 = 1");

        $query->leftJoin('CS.Cliente C');
		$query->leftJoin('C.Many_Cliente_Codigo_Interno MCI');
		$query->leftJoin('C.Cliente_Conformidad CC');
		$query->leftJoin('C.Documento_Tipo DT');
		$query->leftJoin('CS.Sucursal S');
		$query->leftJoin('CS.Sexo SE');
		$query->leftJoin('CS.Tratamiento T');
		$query->leftJoin('CS.Provincia P');
		$query->leftJoin('CS.Ciudad CI');
		

        return $query;
    }
	
	
    //ojo, se supone que aca ya llega todo validado por el controller
    //revisar, agregar tansacciones...
    public function ingresar_clientes($array_data,$sucursal_id,$config=array())
    {
	
        $clientes_ingresados = array();
        if(isset($array_data['cliente']['documento_tipo_id']))
        {

            foreach($array_data['cliente']['documento_tipo_id'] as $key=>$value)
            {
                $cliente=new Cliente();
                $q=$cliente->get_all();
                $q->addWhere('cliente_field_numero_documento = ?', $array_data['cliente']['cliente_field_numero_documento'][$key]);
                $q->addWhere('documento_tipo_id = ?'		 , $array_data['cliente']['documento_tipo_id'][$key]);
                $registro = $q->fetchOne(); 
                
                if(!$registro)
                {
                    //no existe registro, ingreso uno nuevo...
                    $registro = new Cliente();
                    $registro->cliente_field_numero_documento =	$array_data['cliente']['cliente_field_numero_documento'][$key];
                    $registro->documento_tipo_id              =	$array_data['cliente']['documento_tipo_id'][$key];
                    $registro->save();
                }
                //puede ser que no venga la conformidad...
                //cuidado aca, se puede mandar por post igual desde un form q no lo tenga y pisa el dato
                if(isset($array_data['cliente']['cliente_conformidad_id'][$key]))
                {
                    $registro->cliente_conformidad_id = $array_data['cliente']['cliente_conformidad_id'][$key];
                    $registro->save();
                }

                $clientes_ingresados[]=$registro->id;

                #me fijo si existe el cliente para HONDA
                $busqueda_honda = new Cliente_Sucursal();
                $q = $busqueda_honda->get_all();
                $q->addWhere('sucursal_id = ?',1000);
                $q->addWhere('cliente_id = ?',$registro->id);
                $cliente_honda = $q->fetchOne();
				
                if(!$cliente_honda)
                {
                        $this->_ingresar_cliente(1000,$array_data,$registro->id,$key);
                }
                $this->_ingresar_cliente($sucursal_id,$array_data,$registro->id,$key);
				
            }
            return $clientes_ingresados;
        }
        return false;
    }
	
    private function _ingresar_cliente($sucursal_id, $array_data, $cliente_id, $key, $config=array())
    {	

        $busqueda = new Cliente_Sucursal();
        $q=$busqueda->get_all();
        $q->addWhere('cliente_id = ?' ,$cliente_id);
        $q->addWhere('sucursal_id = ?',$sucursal_id);
        $cliente_sucursal = $q->fetchOne();
     
        if(!$cliente_sucursal)
        {
            $cliente_sucursal=new Cliente_Sucursal();
            $cliente_sucursal->cliente_id = $cliente_id;
            $cliente_sucursal->sucursal_id = $sucursal_id;
            $cliente_sucursal->save();
        }

        $cliente_sucursal->cliente_sucursal_field_nombre = $array_data['cliente_sucursal']['cliente_sucursal_field_nombre'][$key];
        $cliente_sucursal->cliente_sucursal_field_apellido = $array_data['cliente_sucursal']['cliente_sucursal_field_apellido'][$key];
        $cliente_sucursal->cliente_sucursal_field_razon_social = $array_data['cliente_sucursal']['cliente_sucursal_field_razon_social'][$key];
        $cliente_sucursal->cliente_sucursal_field_direccion_calle = $array_data['cliente_sucursal']['cliente_sucursal_field_direccion_calle'][$key];
        $cliente_sucursal->cliente_sucursal_field_direccion_numero = $array_data['cliente_sucursal']['cliente_sucursal_field_direccion_numero'][$key];
        $cliente_sucursal->cliente_sucursal_field_direccion_depto = $array_data['cliente_sucursal']['cliente_sucursal_field_direccion_depto'][$key];
        $cliente_sucursal->cliente_sucursal_field_direccion_piso = $array_data['cliente_sucursal']['cliente_sucursal_field_direccion_piso'][$key];
        $cliente_sucursal->cliente_sucursal_field_direccion_codigo_postal = $array_data['cliente_sucursal']['cliente_sucursal_field_direccion_codigo_postal'][$key];
        $cliente_sucursal->cliente_sucursal_field_telefono_particular_codigo = $array_data['cliente_sucursal']['cliente_sucursal_field_telefono_particular_codigo'][$key];
        $cliente_sucursal->cliente_sucursal_field_telefono_particular_numero = $array_data['cliente_sucursal']['cliente_sucursal_field_telefono_particular_numero'][$key];
        $cliente_sucursal->cliente_sucursal_field_telefono_laboral_codigo = $array_data['cliente_sucursal']['cliente_sucursal_field_telefono_laboral_codigo'][$key];
        $cliente_sucursal->cliente_sucursal_field_telefono_laboral_numero = $array_data['cliente_sucursal']['cliente_sucursal_field_telefono_laboral_numero'][$key];
        $cliente_sucursal->cliente_sucursal_field_telefono_movil_codigo = $array_data['cliente_sucursal']['cliente_sucursal_field_telefono_movil_codigo'][$key];
        $cliente_sucursal->cliente_sucursal_field_telefono_movil_numero = $array_data['cliente_sucursal']['cliente_sucursal_field_telefono_movil_numero'][$key];
        $cliente_sucursal->cliente_sucursal_field_fax_codigo = $array_data['cliente_sucursal']['cliente_sucursal_field_fax_codigo'][$key];
        $cliente_sucursal->cliente_sucursal_field_fax_numero = $array_data['cliente_sucursal']['cliente_sucursal_field_fax_numero'][$key];
        $cliente_sucursal->cliente_sucursal_field_fax_numero = $array_data['cliente_sucursal']['cliente_sucursal_field_fax_numero'][$key];
        $cliente_sucursal->cliente_sucursal_field_email = $array_data['cliente_sucursal']['cliente_sucursal_field_email'][$key];

        if ( preg_match("#([0-9]{1,2})-([0-9]{1,2})-([0-9]{4})#", $array_data['cliente_sucursal']['cliente_sucursal_field_fecha_nacimiento'][$key]) )
        {
                $arr 	= explode("-", $array_data['cliente_sucursal']['cliente_sucursal_field_fecha_nacimiento'][$key]);
                $cliente_sucursal->cliente_sucursal_field_fecha_nacimiento = $arr[2] . "-" . $arr[1] . "-" . $arr[0];
        }else{
                $cliente_sucursal->cliente_sucursal_field_fecha_nacimiento = FALSE;
        }

        $cliente_sucursal->sexo_id = $array_data['cliente_sucursal']['sexo_id'][$key];
        $cliente_sucursal->tratamiento_id = $array_data['cliente_sucursal']['tratamiento_id'][$key];
        //$cliente->pais_id = $array_data['cliente_sucursal']['pais_id'][$key];
        $cliente_sucursal->provincia_id = $array_data['cliente_sucursal']['provincia_id'][$key];
        $cliente_sucursal->ciudad_id = $array_data['cliente_sucursal']['ciudad_id'][$key];
        $cliente_sucursal->save();

    }
}