<?php

/**
 * Cliente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Cliente.php 328 2012-10-18 05:00:35Z slopez $
 */
class Cliente extends BaseCliente
{
   public function setUp() {

		$this->actAs('Timestampable');
		$this->actAs('SoftDelete');

		$this->hasOne('Documento_Tipo', array(
            'local' => 'documento_tipo_id',
            'foreign' => 'id'
        ));

		$this->hasOne('Cliente_Conformidad', array(
            'local' => 'cliente_conformidad_id',
            'foreign' => 'id'
        ));

		$this->hasMany('Cliente_Sucursal', array(
            'local' => 'id',
            'foreign' => 'cliente_id'
        ));

		$this->hasMany('Tsi', array(
            'local' => 'id',
            'foreign' => 'cliente_id'
        ));

		$this->hasMany('Encuesta_Nos', array(
            'local' => 'id',
            'foreign' => 'cliente_id'
        ));

		$this->hasMany('Tarjeta_Garantia as Many_Tarjeta_Garantia', array(
                'refClass' => 'Tarjeta_Garantia_M_Cliente',
                'local' => 'cliente_id',
                'foreign' => 'tarjeta_garantia_id'
            )
        );

		$this->hasMany('Cliente_Codigo_Interno as Many_Cliente_Codigo_Interno', array(
                'refClass' => 'Cliente_M_Cliente_Codigo_Interno',
                'local' => 'cliente_id',
                'foreign' => 'cliente_codigo_interno_id'
            )
        );


	}

	public function get_all()
	{
		$query = Doctrine_Query::create();
		$query->from(get_class($this) .' Cliente ');
		$query->leftJoin('Cliente.Cliente_Sucursal Cliente_Sucursal ');
		$query->leftJoin('Cliente_Sucursal.Sucursal Sucursal ');
		$query->where("1 = 1");
		return $query;
	}

}