<?php

/**
 * Cliente_Conformidad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Cliente_Conformidad extends BaseCliente_Conformidad
{
    public function setUp() {

        $this->actAs('Timestampable');
        $this->actAs('SoftDelete');


	$this->hasMany('Cliente', array(
            'local' => 'id',
            'foreign' => 'cliente_conformidad_id'
            ));
    }

    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this) .' C ');
        $query->where("1 = 1");
        return $query;
    }
}