<?php

/**
 * Cliente_M_Cliente_Codigo_Interno
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Cliente_M_Cliente_Codigo_Interno.php 97 2012-08-01 21:57:04Z mprado $
 */
class Cliente_M_Cliente_Codigo_Interno extends BaseCliente_M_Cliente_Codigo_Interno
{
    public function setUp() {

	$this->hasOne('Cliente', array(
                'local' => 'cliente_id',
                'foreign' => 'id',
		'onDelete' => 'CASCADE'
            ));
        
        $this->hasOne('Cliente_Codigo_Interno', array(
                'local' => 'cliente_codigo_interno_id',
                'foreign' => 'id',
                'onDelete' => 'CASCADE'
            ));

    }

    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this));
        $query->where("1 = 1");
        return $query;
    }

}