<?php

/**
 * Cliente_Codigo_Interno
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Cliente_Codigo_Interno.php 97 2012-08-01 21:57:04Z mprado $
 */
class Cliente_Codigo_Interno extends BaseCliente_Codigo_Interno
{
    public function setUp() { 
        
        $this->actAs('Timestampable');
        

        $this->hasMany('Cliente as Many_Cliente', array(
            'refClass' => 'Cliente_M_Cliente_Codigo_Interno',
            'local' => 'cliente_codigo_interno_id',
            'foreign' => 'cliente_id'
        ));
		
    }
	
	
    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this));
        $query->where("1 = 1");
        return $query;
    }
}