<?php

/**
 * Codigo_Radio_Solicitud
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Codigo_Radio_Solicitud.php 98 2012-08-02 19:31:55Z mprado $
 */
class Codigo_Radio_Solicitud extends BaseCodigo_Radio_Solicitud
{
    public function setUp() { 
	
        $this->actAs('Timestampable');
		
	$this->hasOne('Codigo_Radio_Solicitud_Estado', array(
            'local' => 'codigo_radio_solicitud_estado_id',
            'foreign' => 'id'
            ));
	
        $this->hasOne('Unidad', array(
            'local' => 'unidad_id',
            'foreign' => 'id'
            ));
	
        $this->hasOne('Sucursal', array(
            'local' => 'sucursal_id',
            'foreign' => 'id'
            ));
	
        $this->hasOne('Admin as Admin_Alta', array(
            'local' => 'codigo_radio_solicitud_field_admin_alta_id',
            'foreign' => 'id'
            ));
	
        $this->hasOne('Admin as Admin_Modifica', array(
            'local' => 'codigo_radio_solicitud_field_admin_modifica_id',
            'foreign' => 'id'
            ));
    }

    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this) .' CODIGO_RADIO_SOLICITUD ');
        $query->leftJoin('CODIGO_RADIO_SOLICITUD.Codigo_Radio_Solicitud_Estado CODIGO_RADIO_SOLICITUD_ESTADO ');
        $query->leftJoin('CODIGO_RADIO_SOLICITUD.Sucursal SUCURSAL ');
        $query->leftJoin('CODIGO_RADIO_SOLICITUD.Admin_Alta ADMIN_ALTA ');
        $query->leftJoin('CODIGO_RADIO_SOLICITUD.Admin_Modifica ADMIN_MODIFICA ');

        $query->leftJoin('CODIGO_RADIO_SOLICITUD.Unidad UNIDAD ');
        $query->leftJoin('UNIDAD.Vin_Procedencia_Ktype VP ');
        $query->leftJoin('UNIDAD.Auto_Version AV');
        $query->leftJoin('AV.Auto_Modelo AM ON AV.auto_modelo_id = AM.id');
        $query->leftJoin('AM.Auto_Marca AMARCA ON AM.auto_marca_id = AMARCA.id');
        $query->leftJoin('UNIDAD.Unidad_Color_Exterior CE ');
        $query->leftJoin('UNIDAD.Unidad_Color_Interior CI ');
        $query->leftJoin('UNIDAD.Auto_Fabrica AF ');
        $query->leftJoin('UNIDAD.Auto_Anio AA ');
        $query->leftJoin('UNIDAD.Auto_Puerta_Cantidad PC ');
        $query->leftJoin('UNIDAD.Auto_Transmision AT ');
        $query->leftJoin('UNIDAD.Auto_Combustible AC ');
        $query->leftJoin('UNIDAD.Unidad_Estado_Garantia ');
        $query->leftJoin('UNIDAD.Unidad_Estado ');
        $query->leftJoin('UNIDAD.Many_Unidad_Codigo_Interno ');


        $query->where("1 = 1");

        return $query;
    }
}