<?php

/**
 * Codigo_Radio_Solicitud_Estado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Codigo_Radio_Solicitud_Estado.php 97 2012-08-01 21:57:04Z mprado $
 */
class Codigo_Radio_Solicitud_Estado extends BaseCodigo_Radio_Solicitud_Estado
{
    public function setUp() {

        $this->actAs('Timestampable');
        $this->actAs('SoftDelete');

        $this->hasMany('Codigo_Radio_Solicitud', array(
            'local' => 'id',
            'foreign' => 'codigo_radio_solicitud_estado_id',
            ));
    }

    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this));
        $query->where("1 = 1");
        return $query;
    }
}