<?php

/**
 * Comunicacion_Aviso
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Comunicacion_Aviso.php 616 2013-01-15 16:30:11Z agusquiroga $
 */
class Comunicacion_Aviso extends BaseComunicacion_Aviso
{

	public function setUp()
	{
		parent::setUp();
		$this->hasOne('Publicidad_Producto', array(
				'foreign' => 'id',
				'local' => 'comunicacion_producto_id'));
	}

	public function get_all()
	{
		$query = Doctrine_Query::create();
		$query->from('Comunicacion_Aviso Comunicacion_Aviso');
		$query->leftJoin('Comunicacion_Aviso.Publicidad_Producto Publicidad_Producto');
		$query->where("1 = 1");
		return $query;
	}

}