<?php

/**
 * Comunicacion_Folleto_Pdf
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Comunicacion_Folleto_Pdf.php 1046 2013-05-21 19:32:50Z agusquiroga $
 */
class Comunicacion_Folleto_Pdf extends BaseComunicacion_Folleto_Pdf
{
	public function get_all()
	{
		$query = Doctrine_Query::create();
		$query->from(get_class($this));
		$query->where("1 = 1");
		return $query;
	}

}