<?php

/**
 * Comunicacion_Folleto
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Comunicacion_Folleto.php 662 2013-01-24 21:08:44Z agusquiroga $
 */
class Comunicacion_Folleto extends BaseComunicacion_Folleto
{

	public function setUp()
	{
		parent::setUp();
	}

	public function get_all()
	{
		$query = Doctrine_Query::create();
		$query->from(get_class($this));
		$query->where("1 = 1");
		return $query;
	}

}