<?php

/**
 * Doctrine__Record__Abstract
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Doctrine__Record__Abstract.php 92 2012-08-01 16:51:56Z agusquiroga $
 */
class Doctrine__Record__Abstract extends BaseDoctrine__Record__Abstract
{

}