<?php

/**
 * Documento_Tipo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Documento_Tipo.php 97 2012-08-01 21:57:04Z mprado $
 */
class Documento_Tipo extends BaseDocumento_Tipo
{
    public function setUp() {
		
        $this->actAs('Timestampable');
        $this->actAs('SoftDelete');

        $this->hasMany('Cliente', array(
            'local' => 'id',
            'foreign' => 'documento_tipo_id',
            ));
    }

    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this));
        $query->where("1 = 1");
        return $query;
    }
}