<?php

/**
 * Empresa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Empresa.php 97 2012-08-01 21:57:04Z mprado $
 */
class Empresa extends BaseEmpresa
{
    public function setUp() {

        $this->actAs('Timestampable');
        //$this->actAs('SoftDelete');

        $this->hasMany('Unidad', array(
            'local' => 'id',
            'foreign' => 'empresa_id'
            ));


        $this->hasMany('Sucursal', array(
            'local' => 'id',
            'foreign' => 'empresa_id'
            ));

        $this->hasOne('Backend_Estado', array(
            'local' => 'backend_estado_id',
            'foreign' => 'id'
        ));
    }

    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this));
        $query->where("1 = 1");
        return $query;
    }
}