<?php

/**
 * Encuesta_Nos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Encuesta_Nos.php 97 2012-08-01 21:57:04Z mprado $
 */
class Encuesta_Nos extends BaseEncuesta_Nos
{
    public function setUp() { 
	
        $this->actAs('Timestampable');
		
	$this->hasOne('Tarjeta_Garantia', array(
            'local' => 'tarjeta_garantia_id',
            'foreign' => 'id'
            ));
		
	$this->hasOne('Cliente', array(
            'local' => 'cliente_id',
            'foreign' => 'id'
            ));
		
	$this->hasOne('Sexo', array(
            'local' => 'sexo_id',
            'foreign' => 'id'
            ));
		
	$this->hasOne('Encuesta_Nos_Edad', array(
            'local' => 'encuesta_nos_edad_id',
            'foreign' => 'id'
            ));
		
	$this->hasOne('Encuesta_Nos_Grupo_Familiar', array(
            'local' => 'encuesta_nos_grupo_familiar_id',
            'foreign' => 'id'
            ));
		
	$this->hasOne('Encuesta_Nos_Ocupacion', array(
            'local' => 'encuesta_nos_ocupacion_id',
            'foreign' => 'id'
            ));
		
	$this->hasOne('Encuesta_Nos_Financiacion', array(
            'local' => 'encuesta_nos_financiacion_id',
            'foreign' => 'id'
            ));
		
	$this->hasOne('Encuesta_Nos_Tipo_Automovil', array(
            'local' => 'encuesta_nos_tipo_automovil_id',
            'foreign' => 'id'
            ));
		
	$this->hasOne('Encuesta_Nos_Conductor', array(
            'local' => 'encuesta_nos_conductor_id',
            'foreign' => 'id'
            ));
		
	$this->hasOne('Encuesta_Nos_Estado', array(
            'local' => 'encuesta_nos_estado_id',
            'foreign' => 'id'
            ));
		
	$this->hasMany('Encuesta_Nos_Opinion_Interes as Many_Encuesta_Nos_Opinion_Interes', array(
                'refClass' => 'Encuesta_Nos_M_Encuesta_Nos_Opinion_Interes',
                'local' => 'encuesta_nos_id',
                'foreign' => 'encuesta_nos_opinion_interes_id'
            ));		
		
    }
	
	//-------------------------------------
	
    public function get_all()
    {

        $query = Doctrine_Query::create();
        $query->from(get_class($this) . ' ENCUESTA_NOS ');
        $query->where("1 = 1");

        $query->leftJoin('ENCUESTA_NOS.Tarjeta_Garantia TARJETA_GARANTIA ');
        $query->leftJoin('ENCUESTA_NOS.Encuesta_Nos_Estado ENCUESTA_NOS_ESTADO ');
        $query->leftJoin('TARJETA_GARANTIA.Unidad UNIDAD ');
        $query->leftJoin('UNIDAD.Auto_Version AUTO_VERSION ');
        $query->leftJoin('AUTO_VERSION.Auto_Modelo AUTO_MODELO ');


        $query->leftJoin('ENCUESTA_NOS.Cliente CLIENTE ');
        $query->leftJoin('CLIENTE.Cliente_Sucursal CLIENTE_SUCURSAL ');


        $query->addWhere("TARJETA_GARANTIA.sucursal_id = CLIENTE_SUCURSAL.sucursal_id");
        //$query->addWhere("ENCUESTA_NOS.cliente_id = CLIENTE_SUCURSAL.cliente_id");

        return $query;
    }
}