<?php

/**
 * Encuesta_Nos_Opinion_Interes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Encuesta_Nos_Opinion_Interes.php 120 2012-08-14 16:04:21Z mprado $
 */
class Encuesta_Nos_Opinion_Interes extends BaseEncuesta_Nos_Opinion_Interes
{
    public function setUp() {
		
		$this->actAs('Timestampable');
		$this->actAs('SoftDelete');
		
		$this->hasMany('Encuesta_Nos as Many_Encuesta_Nos', array(
                'refClass' => 'Encuesta_Nos_M_Encuesta_Nos_Opinion_Interes',
                'local' => 'encuesta_nos_opinion_interes_id',
                'foreign' => 'encuesta_nos_id'
            )
        );
		
		
	}
	
	public function get_all()
	{
		$query = Doctrine_Query::create();
		$query->from(get_class($this));
		$query->where("1 = 1");
		return $query;
	}
}