<?php

/**
 * Encuesta_Nos_Estado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Encuesta_Nos_Estado.php 98 2012-08-02 19:31:55Z mprado $
 */
class Encuesta_Nos_Estado extends BaseEncuesta_Nos_Estado
{
    public function setUp() {
		
	$this->actAs('Timestampable');
	$this->actAs('SoftDelete');
		
	$this->hasMany('Encuesta_Nos', array(
            'local' => 'id',
            'foreign' => 'encuesta_nos_estado_id',
            ));
    }

    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this));
        $query->where("1 = 1");
        return $query;
    }
}