<?php

/**
 * Encuesta_Nos_M_Encuesta_Nos_Opinion_Interes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Encuesta_Nos_M_Encuesta_Nos_Opinion_Interes.php 109 2012-08-09 18:04:11Z agusquiroga $
 */
class Encuesta_Nos_M_Encuesta_Nos_Opinion_Interes extends BaseEncuesta_Nos_M_Encuesta_Nos_Opinion_Interes
{
	public function setUp()
	{
		parent::setUp();
		$this->hasOne('Encuesta_Nos', array(
				'local' => 'encuesta_nos_id',
				'foreign' => 'id'));
	
		$this->hasOne('Encuesta_Nos_Opinion_Interes', array(
				'local' => 'encuesta_nos_opinion_interes_id',
				'foreign' => 'id'));
	}

}