<?php

/**
 * Frt_Seccion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Frt_Seccion.php 255 2012-09-27 19:36:31Z slopez $
 */
class Frt_Seccion extends BaseFrt_Seccion
{
	 public function setUp() {
		
        $this->actAs('Timestampable');
		
		$this->hasMany('Frt as Frt', array(
            'local' => 'id',
            'foreign' => 'frt_seccion_id'
            ));

        
    }
	
    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this));
        $query->where("1 = 1");
        return $query;
    }
}