<?php

/**
 * Frt_Hora
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Frt_Hora.php 399 2012-11-13 20:51:34Z mprado $
 */
class Frt_Hora extends BaseFrt_Hora
{
	public function setUp() {
		
        $this->actAs('Timestampable');
		
        $this->hasOne('Frt', array(
            'local'     => 'frt_id',
            'foreign'   => 'id'
            ));
		
        $this->hasOne('Auto_Modelo' , array(
            'local'     => 'auto_modelo_id',
            'foreign'   => 'id'
        ));
        
        $this->hasOne('Auto_Anio', array(
            'local'     => 'auto_anio_id',
            'foregin'   => 'id'
        ));        
    }
	
    public function get_all()
    {
        $query = Doctrine_Query::create();
        
        $query->from(get_class($this) . ' Frt_Hora');
	
        //Left Join FRT
        $query->leftJoin('Frt_Hora.Frt Frt ');
	
        //Left Join FRT Seccion
        $query->leftJoin('Frt.Frt_Seccion Frt_Seccion ');
        
        //Left Join FRT Auto Modelo
        $query->leftJoin('Frt_Hora.Auto_Modelo Auto_Modelo ');
        
        //Left Join FRT Auto Anio
        $query->leftJoin('Frt_Hora.Auto_Anio Auto_Anio ');
        
        $query->where("1 = 1");
        return $query;
    }
}