<?php

/**
 * Grupo_M_Backend_Menu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Grupo_M_Backend_Menu.php 205 2012-09-10 20:22:31Z slopez $
 */
class Grupo_M_Backend_Menu extends BaseGrupo_M_Backend_Menu
{
	
	public function setUp() {
		
		
		$this->hasOne('Backend_Menu', array(
                'local' => 'backend_menu_id',
                'foreign' => 'id',
				'onDelete' => 'CASCADE'
            )
        );
        $this->hasOne('Grupo', array(
                'local' => 'grupo_id',
                'foreign' => 'id',
				'onDelete' => 'CASCADE'
            )
        );
		
	}
	
	public function get_all()
	{
		$query = Doctrine_Query::create();
		$query->from(get_class($this));
		$query->where("1 = 1");
		return $query;
	}

	


}