<?php

/**
 * Grupo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Grupo.php 97 2012-08-01 21:57:04Z mprado $
 */
class Grupo extends BaseGrupo
{
    public function setUp() {
		
	$this->actAs('Timestampable');
		
		
	$this->hasMany('Admin as Many_Admin', array(
            'refClass' => 'Admin_M_Grupo',
            'local' => 'grupo_id',
            'foreign' => 'admin_id'
            ));
		
	$this->hasMany('Backend_Menu as Many_Backend_Menu', array(
            'refClass' => 'Grupo_M_Backend_Menu',
            'local' => 'grupo_id',
            'foreign' => 'backend_menu_id'
            ));
		
    }

    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this));
        $query->where("1 = 1");
        return $query;
    }
}