<?php

/**
 * Hma
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Hma extends BaseHma
{
     public function setUp() {

        $this->actAs('Timestampable');

        $this->hasMany('Hma_Adjunto', array(
            'local' => 'id',
            'foreign' => 'hma_id',
            ));
            
        $this->hasOne('Admin', array(
            'local' => 'admin_id',
            'foreign' => 'id',
            ));
    }


    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this) .' HMA ');
        $query->where("1 = 1");
        $query->leftJoin('HMA.Hma_Adjunto HMA_ADJUNTO');		
        return $query;
    }
}