<?php

/**
 * Hma_Adjunto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Hma_Adjunto extends BaseHma_Adjunto
{
    public function setUp() {
	
	$this->actAs('Timestampable');
		
	$this->hasOne('Hma', array(
            'local' => 'hma_id',
            'foreign' => 'id'
            ));		
    }

    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this));
        $query->where("1 = 1");		
        return $query;
    }
}