<?php

/**
 * Libro_Servicio_Adjunto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Libro_Servicio_Adjunto.php 98 2012-08-02 19:31:55Z mprado $
 */
class Libro_Servicio_Adjunto extends BaseLibro_Servicio_Adjunto
{
    public function setUp() {
	
	$this->actAs('Timestampable');
		
	$this->hasOne('Libro_Servicio', array(
            'local' => 'libro_servicio_id',
            'foreign' => 'id'
            ));
		
    }

    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this));
        $query->where("1 = 1");
        return $query;
    }

}