<?php

/**
 * Material_Precio_Fob
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Material_Precio_Fob.php 225 2012-09-19 13:06:46Z slopez $
 */
class Material_Precio_Fob extends BaseMaterial_Precio_Fob
{
	
	public function setUp() {
		
        $this->actAs('Timestampable');
		
		$this->hasOne('Moneda', array(
            'local' => 'moneda_id',
            'foreign' => 'id'
            ));
		$this->hasOne('Material', array(
            'local' => 'material_id',
            'foreign' => 'id'
            ));
        
    }

    public function get_all($config = array())
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this) .' Material_Precio_Fob ');
		$query->leftJoin('Material_Precio_Fob.Moneda Mondeda ');
		$query->leftJoin('Material_Precio_Fob.Material Material ');
        $query->where("1 = 1");
        
		
		return $query;
		
    }
	
	
}