<?php

/**
 * Material_Facturacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Material_Facturacion.php 292 2012-10-03 18:44:29Z slopez $
 */
class Material_Facturacion extends BaseMaterial_Facturacion
{
	public function get_all()
	{
		$query = Doctrine_Query::create();
		$query->from(get_class($this) .' MATERIAL ');
		$query->where("1 = 1");
			
		return $query;
	}
}