<?php

/**
 * Migration_Version
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Migration_Version.php 92 2012-08-01 16:51:56Z agusquiroga $
 */
class Migration_Version extends BaseMigration_Version
{

}