<?php

/**
 * Noticia_Seccion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Noticia_Seccion.php 97 2012-08-01 21:57:04Z mprado $
 */
class Noticia_Seccion extends BaseNoticia_Seccion
{
    public function setUp() {
		
	$this->actAs('Timestampable');
	$this->actAs('SoftDelete');
		
	$this->hasMany('Noticia', array(
            'local' => 'id',
            'foreign' => 'noticia_seccion_id',
            ));	
               
        $this->hasOne('Backend_Estado', array(
            'local' => 'backend_estado_id',
            'foreign' => 'id',
            )
        );		
		
    }

    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this) . ' N ');
        $query->where("1 = 1");

        $query->leftJoin('N.Backend_Estado');
        return $query;
    }
}