<?php

/**
 * Noticia_Imagen
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Noticia_Imagen.php 135 2012-08-15 17:15:58Z slopez $
 */
class Noticia_Imagen extends BaseNoticia_Imagen
{
	
	public function setUp() {
	
		$this->actAs('Timestampable');
		
		$this->hasOne('Noticia', array(
            'local' => 'noticia_id',
            'foreign' => 'id'
        ));
		
	}

	public function get_all()
	{
		$query = Doctrine_Query::create();
		$query->from(get_class($this));
		$query->where("1 = 1");
		return $query;
	}
	
	
}