<?php

/**
 * Noticia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Noticia.php 97 2012-08-01 21:57:04Z mprado $
 */
class Noticia extends BaseNoticia
{
    
    
    public function setUp() { 
		 
		//$this->actAs('Timestampable');
		//$this->actAs('SoftDelete');
		
		$this->hasMany('Noticia_Imagen', array(
            'local' => 'id',
            'foreign' => 'noticia_id',
            )
        );
		
		$this->hasMany('Noticia_Adjunto', array(
            'local' => 'id',
            'foreign' => 'noticia_id',
            )
        );
		
		$this->hasOne('Backend_Estado', array(
            'local' => 'backend_estado_id',
            'foreign' => 'id'
        ));
		/*
		$this->hasMany('Noticia_Imagen', array(
            'local' => 'id',
            'foreign' => 'noticia_id'
        ));
		*/
		/*
		$this->hasOne('sucursal', array(
            'local' => 'sucursal_id',
            'foreign' => 'id'
        ));
		*/
		$this->hasOne('Noticia_Seccion', array(
            'local' => 'noticia_seccion_id',
            'foreign' => 'id'
        ));
	}
    
    public function get_all()
	{
		$query = Doctrine_Query::create();
		$query->from(get_class($this) .' NOTICIA ');
		$query->where("1 = 1");
		
		$query->leftJoin('NOTICIA.Noticia_Seccion NS');
		$query->leftJoin('NOTICIA.Noticia_Imagen NI');
		$query->leftJoin('NOTICIA.Noticia_Adjunto NA');
		$query->leftJoin('NOTICIA.Backend_Estado BE');
		
		$query->where('1 = 1');
		return $query;
	}

}