<?php

/**
 * Pedsp_Pedido
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Pedsp_Pedido.php 526 2012-12-12 20:03:21Z agusquiroga $
 */
class Pedsp_Pedido extends BasePedsp_Pedido
{

}