<?php

/**
 * Provincia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Provincia.php 97 2012-08-01 21:57:04Z mprado $
 */
class Provincia extends BaseProvincia
{
    public function setUp() 
    {
	
	$this->actAs('Timestampable');
		
	$this->hasMany('Sucursal', array(
                'local' => 'id',
                'foreign' => 'provincia_id'
                ));
		
        $this->hasOne('Pais', array(
                'local' => 'pais_id',
                'foreign' => 'id'
                ));
        
        $this->hasMany('Cliente_Sucursal', array(
                'local' => 'cliente_id',
                'foreign' => 'id'
                ));
		
	}
        
    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this) . ' P ');
        $query->where("1 = 1");

        $query->leftJoin('P.Pais PA ');

        return $query;
    }
}