<?php

/**
 * Publicidad_Imagen
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Publicidad_Imagen.php 98 2012-08-02 19:31:55Z mprado $
 */
class Publicidad_Imagen extends BasePublicidad_Imagen
{   
    public function setUp() {
	
	$this->actAs('Timestampable');
		
	$this->hasOne('Publicidad', array(
            'local' => 'publicidad_id',
            'foreign' => 'id'
            ));
		
    }

    public function get_all()
    {
	$query = Doctrine_Query::create();
	$query->from(get_class($this));
	$query->where("1 = 1");
	return $query;
    }
}