<?php

/**
 * Publicidad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Publicidad.php 98 2012-08-02 19:31:55Z mprado $
 */
class Publicidad extends BasePublicidad
{
    public function setUp() { 

        $this->actAs('Timestampable');
	$this->actAs('SoftDelete');
		
	$this->hasOne('Publicidad_Medida', array(
            'local' => 'publicidad_medida_id',
            'foreign' => 'id'
            ));
		
	$this->hasOne('Publicidad_Ubicacion', array(
            'local' => 'publicidad_ubicacion_id',
            'foreign' => 'id'
            ));
		
	$this->hasOne('Publicidad_Medio', array(
            'local' => 'publicidad_medio_id',
            'foreign' => 'id'
            ));
		
	$this->hasOne('Publicidad_Producto', array(
            'local' => 'publicidad_producto_id',
            'foreign' => 'id'
            ));
		
	$this->hasMany('Publicidad_Imagen', array(
            'local' => 'id',
            'foreign' => 'publicidad_id',
            ));
		
       
        $this->hasMany('Publicidad_Imagen_Medio', array(
            'local' => 'id',
            'foreign' => 'publicidad_id',
            ));		
		
    }
	
	
    public function get_all()
    {
	$query = Doctrine_Query::create();
	$query->from(get_class($this) .' PUBLICIDAD ');
	$query->where("1 = 1");
		
	$query->leftJoin('PUBLICIDAD.Publicidad_Medida PUBLICIDAD_MEDIDA ');
	$query->leftJoin('PUBLICIDAD.Publicidad_Ubicacion PUBLICIDAD_UBICACION ');
	$query->leftJoin('PUBLICIDAD.Publicidad_Medio PUBLICIDAD_MEDIO ');
	$query->leftJoin('PUBLICIDAD.Publicidad_Producto PUBLICIDAD_PRODUCTO ');
	$query->leftJoin('PUBLICIDAD.Publicidad_Imagen PUBLICIDAD_IMAGEN ');
	$query->leftJoin('PUBLICIDAD.Publicidad_Imagen_Medio PUBLICIDAD_IMAGEN_MEDIO ');
		
	return $query;
    }
}