<?php

/**
 * Reclamo_Garantia_Material
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Reclamo_Garantia_Material.php 465 2012-11-22 12:40:59Z slopez $
 */
class Reclamo_Garantia_Material extends BaseReclamo_Garantia_Material
{
    public function setUp() { 
	
        $this->actAs('Timestampable');
		
	$this->hasOne('Reclamo_Garantia_Version', array(
            'local' => 'reclamo_garantia_version_id',
            'foreign' => 'id',
			'onDelete' => 'CASCADE'
            ));
		
	$this->hasOne('Material_Facturacion', array(
            'local' => 'material_facturacion_field_documento_sap_id',
            'foreign' => 'material_facturacion_field_documento_sap_id'
            ));
	
        $this->hasOne('Material', array(
            'local' => 'material_id',
            'foreign' => 'id'
            ));
		
    }	

    public function get_all()
    {

        $query = Doctrine_Query::create();
        $query->from(get_class($this) . ' RECLAMO_GARANTIA_MATERIAL ');
        $query->where("1 = 1");

        return $query;
    }
}