<?php

/**
 * Reclamo_Garantia_Frt
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Reclamo_Garantia_Frt.php 92 2012-08-01 16:51:56Z agusquiroga $
 */
class Reclamo_Garantia_Frt extends BaseReclamo_Garantia_Frt
{

}