<?php

/**
 * Reclamo_Garantia_Codigo_Defecto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Reclamo_Garantia_Codigo_Defecto.php 293 2012-10-03 18:45:14Z slopez $
 */
class Reclamo_Garantia_Codigo_Defecto extends BaseReclamo_Garantia_Codigo_Defecto
{
	public function setUp() { 
		$this->actAs('Timestampable');
		$this->actAs('SoftDelete');
		
		
		
		$this->hasOne('Reclamo_Garantia_Codigo_Defecto_Seccion', array(
                'local' => 'reclamo_garantia_codigo_defecto_seccion_id',
                'foreign' => 'id'
            )
        );
		
	}
	
	//-------------------------------------
	
	public function get_all()
	{
		$query = Doctrine_Query::create();
		$query->from(get_class($this) .' Reclamo_Garantia_Codigo_Defecto ');
		$query->leftJoin('Reclamo_Garantia_Codigo_Defecto.Reclamo_Garantia_Codigo_Defecto_Seccion Reclamo_Garantia_Codigo_Defecto_Seccion ');
		$query->where("1 = 1");
		
		return $query;
	}
	
	public function get_desc($id = FALSE)
	{
		$q = Doctrine_Query::create();
		$q->from(get_class($this));
		$q->where('id = ?',$id);
		$resultado = $q->fetchOne();
		if(!$resultado)
		{
			RETURN FALSE;
		}
		else
		{
			RETURN $resultado['reclamo_garantia_codigo_defecto_field_desc'];
		}
	}
}