<?php

/**
 * Reclamo_Garantia_Valor_Hora_Japon
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Reclamo_Garantia_Valor_Hora_Japon extends BaseReclamo_Garantia_Valor_Hora_Japon
{
	public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this) .' RECLAMO_GARANTIA_VALOR_HORA_JAPON ');
        $query->where("1 = 1");
        return $query;
    }
}