<?php

/**
 * Reclamo_Garantia_Codigo_Sintoma_M_Seccion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Reclamo_Garantia_Codigo_Sintoma_M_Seccion.php 300 2012-10-04 01:59:27Z agusquiroga $
 */
class Reclamo_Garantia_Codigo_Sintoma_M_Seccion extends BaseReclamo_Garantia_Codigo_Sintoma_M_Seccion
{

}