<?php

/**
 * Reclamo_Garantia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Reclamo_Garantia.php 588 2012-12-21 17:11:21Z slopez $
 */
 
 
 /*
 
	TODO no esta tomando el material_id de Reclamo_Garantia_Material_Principal/Secundario cuando el material no existe en la tabla
 */
 
 
class Reclamo_Garantia extends BaseReclamo_Garantia
{
    public function setUp() { 
	
        $this->actAs('Timestampable');
	$this->actAs('SoftDelete');
		
	$this->hasOne('Reclamo_Garantia_Estado', array(
            'local' => 'reclamo_garantia_estado_id',
            'foreign' => 'id'
            ));
		
	$this->hasOne('Reclamo_Garantia as Reenvio_Reclamo_Garantia', array(
            'local' => 'reclamo_garantia_field_reenvio_id',
            'foreign' => 'id'
            ));
		
	$this->hasOne('Tsi', array(
            'local' => 'tsi_id',
            'foreign' => 'id'
            ));
		
	$this->hasOne('Reclamo_Garantia_Codigo_Rechazo_Principal', array(
            'local' => 'reclamo_garantia_codigo_rechazo_principal_id',
            'foreign' => 'id'
            ));
	
        $this->hasOne('Reclamo_Garantia_Codigo_Rechazo_Secundario', array(
            'local' => 'reclamo_garantia_codigo_rechazo_secundario_id',
            'foreign' => 'id'
            ));
		
	$this->hasOne('Admin as Admin_Alta', array(
            'local' => 'reclamo_garantia_field_admin_alta_id',
            'foreign' => 'id'
            ));
	
        $this->hasOne('Admin as Admin_Modifica', array(
            'local' => 'reclamo_garantia_field_admin_modifica_id',
            'foreign' => 'id'
            ));
	
        $this->hasOne('Admin as Admin_Rechaza', array(
            'local' => 'reclamo_garantia_field_admin_rechaza_id',
            'foreign' => 'id'
            ));
	
        $this->hasOne('Admin as Admin_Pre_Aprueba', array(
            'local' => 'reclamo_garantia_field_admin_pre_aprueba_id',
            'foreign' => 'id'
            ));
		
		$this->hasOne('Admin as Admin_Aprueba', array(
            'local' => 'reclamo_garantia_field_admin_aprueba_id',
            'foreign' => 'id'
            ));
		
		$this->hasOne('Unidad_Estado_Garantia', array(
            'local' => 'unidad_estado_garantia_id',
            'foreign' => 'id'
            ));
		
	$this->hasMany('Reclamo_Garantia_Version', array(
            'local' => 'id',
            'foreign' => 'reclamo_garantia_id'
            ));
		
	$this->hasOne('Reclamo_Garantia_Campania', array(
            'local' => 'reclamo_garantia_campania_id',
            'foreign' => 'id'
            ));		
    }	
	
	
    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this) .' RECLAMO_GARANTIA ');
        $query->where("1 = 1");
        $query->leftJoin('RECLAMO_GARANTIA.Tsi TSI');
        $query->leftJoin('TSI.Sucursal SUCURSAL');
        $query->leftJoin('TSI.Unidad UNIDAD');
		$query->leftJoin('UNIDAD.Vin_Procedencia_Ktype VP ');
        $query->leftJoin('UNIDAD.Many_Unidad_Codigo_Interno UCI ');
        $query->leftJoin('UNIDAD.Auto_Version AV ');
        $query->leftJoin('UNIDAD.Unidad_Color_Interior CI ');
        $query->leftJoin('UNIDAD.Unidad_Color_Exterior CE ');
        $query->leftJoin('AV.Auto_Modelo AM ');
        $query->leftJoin('UNIDAD.Auto_Transmision AT ');
        $query->leftJoin('UNIDAD.Auto_Anio AA ');
        $query->leftJoin('UNIDAD.Auto_Puerta_Cantidad PC ');
        //$query->leftJoin('UNIDAD.Unidad_Estado_Garantia UEG ');
		
			
        $query->leftJoin('TSI.Many_Tsi_Tipo_Servicio MANY_TSI_TIPO_SERVICIO ');

        $query->leftJoin('RECLAMO_GARANTIA.Reclamo_Garantia_Estado RECLAMO_GARANTIA_ESTADO');
        $query->leftJoin('RECLAMO_GARANTIA.Reclamo_Garantia_Campania RECLAMO_GARANTIA_CAMPANIA');
        $query->leftJoin('RECLAMO_GARANTIA.Reclamo_Garantia_Codigo_Rechazo_Principal RECLAMO_GARANTIA_CODIGO_RECHAZO_PRINCIPAL');
        $query->leftJoin('RECLAMO_GARANTIA.Reclamo_Garantia_Codigo_Rechazo_Secundario RECLAMO_GARANTIA_CODIGO_RECHAZO_SECUNDARIO');
        $query->leftJoin('RECLAMO_GARANTIA.Reclamo_Garantia_Version RECLAMO_GARANTIA_VERSION');
        $query->leftJoin('RECLAMO_GARANTIA_VERSION.Reclamo_Garantia_Frt RECLAMO_GARANTIA_FRT');
        $query->leftJoin('RECLAMO_GARANTIA_VERSION.Reclamo_Garantia_Material_Principal RECLAMO_GARANTIA_MATERIAL_PRINCIPAL ON RECLAMO_GARANTIA_VERSION.id = RECLAMO_GARANTIA_MATERIAL_PRINCIPAL.reclamo_garantia_version_id AND RECLAMO_GARANTIA_MATERIAL_PRINCIPAL.reclamo_garantia_material_field_material_principal = 1');
        $query->leftJoin('RECLAMO_GARANTIA_VERSION.Reclamo_Garantia_Material_Secundario RECLAMO_GARANTIA_MATERIAL_SECUNDARIO ON RECLAMO_GARANTIA_VERSION.id = RECLAMO_GARANTIA_MATERIAL_SECUNDARIO.reclamo_garantia_version_id AND RECLAMO_GARANTIA_MATERIAL_SECUNDARIO.reclamo_garantia_material_field_material_principal != 1');
        $query->leftJoin('RECLAMO_GARANTIA_MATERIAL_PRINCIPAL.Material MATERIAL_PRINCIPAL');
        $query->leftJoin('RECLAMO_GARANTIA_MATERIAL_SECUNDARIO.Material MATERIAL_SECUNDARIO');

        $query->leftJoin('RECLAMO_GARANTIA_VERSION.Reclamo_Garantia_Version_Adjunto_Transporte RECLAMO_GARANTIA_VERSION_ADJUNTO_TRANSPORTE');
        $query->leftJoin('RECLAMO_GARANTIA_VERSION.Reclamo_Garantia_Version_Adjunto_Rth RECLAMO_GARANTIA_VERSION_ADJUNTO_RTH');
        $query->leftJoin('RECLAMO_GARANTIA_VERSION.Reclamo_Garantia_Version_Adjunto_Trabajo_Tercero RECLAMO_GARANTIA_VERSION_ADJUNTO_TRABAJO_TERCERO');

        $query->leftJoin('RECLAMO_GARANTIA_VERSION.Reclamo_Garantia_Codigo_Sintoma RECLAMO_GARANTIA_CODIGO_SINTOMA');
        $query->leftJoin('RECLAMO_GARANTIA_VERSION.Reclamo_Garantia_Codigo_Defecto RECLAMO_GARANTIA_CODIGO_DEFECTO');
        $query->leftJoin('RECLAMO_GARANTIA_VERSION.Reclamo_Garantia_Version_Trabajo_Tercero RECLAMO_GARANTIA_VERSION_TRABAJO_TERCERO');
        $query->leftJoin('RECLAMO_GARANTIA.Admin_Alta ADMIN_ALTA ');
        $query->leftJoin('RECLAMO_GARANTIA.Admin_Modifica ADMIN_MODIFICA ');
        $query->leftJoin('RECLAMO_GARANTIA.Admin_Rechaza ADMIN_RECHAZA ');
		
		 $query->leftJoin('RECLAMO_GARANTIA.Unidad_Estado_Garantia UNIDAD_ESTADO_GARANTIA');

        return $query;
    }
	
	
	//solo para la grilla cuando no se aplican filtros
	public function get_grid()
	{
		 $q = Doctrine_Query::create();
		 $q->select(	'
						RECLAMO_GARANTIA.id,
						UNIDAD.unidad_field_unidad,
						UNIDAD.unidad_field_vin,
						TSI.tsi_field_fecha_de_egreso,
						SUCURSAL.sucursal_field_desc,
						RECLAMO_GARANTIA.reclamo_garantia_campania_id,
						RECLAMO_GARANTIA_ESTADO.reclamo_garantia_estado_field_desc,
						RECLAMO_GARANTIA.reclamo_garantia_field_fechahora_alta
		 ');
         $q->from('Reclamo_Garantia RECLAMO_GARANTIA');
		 $q->leftJoin('RECLAMO_GARANTIA.Tsi TSI');
		 $q->leftJoin('TSI.Sucursal SUCURSAL');
		 $q->leftJoin('TSI.Unidad UNIDAD');
		 $q->leftJoin('RECLAMO_GARANTIA.Reclamo_Garantia_Estado RECLAMO_GARANTIA_ESTADO');
		 $q->where("1 = 1");
		 
		 RETURN $q;
	}
	
	
	
	
	
	

}