<?php

/**
 * Servicio_Boletin_Categoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Servicio_Boletin_Categoria.php 98 2012-08-02 19:31:55Z mprado $
 */
class Servicio_Boletin_Categoria extends BaseServicio_Boletin_Categoria
{
    public function setUp() {
		
	$this->actAs('Timestampable');
	$this->actAs('SoftDelete');
		
	$this->hasMany('Servicio_Boletin', array(
            'local' => 'id',
            'foreign' => 'servicio_boletin_categoria_id',
            ));		
	}
	
    public function get_all()
    {
	$query = Doctrine_Query::create();
	$query->from(get_class($this) . ' SERVICIO_BOLETIN_CATEGORIA ');
	$query->where("1 = 1");
	return $query;
    }
}