<?php

/**
 * Servicio_Noticia_Adjunto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Servicio_Noticia_Adjunto extends BaseServicio_Noticia_Adjunto
{
	public function get_all()
    {
	$query = Doctrine_Query::create();
	$query->from(get_class($this));
	$query->where("1 = 1");
	return $query;
    }
}