<?php

/**
 * Servicio_Reporte_Tecnico_Rth
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Servicio_Reporte_Tecnico_Rth.php 98 2012-08-02 19:31:55Z mprado $
 */
class Servicio_Reporte_Tecnico_Rth extends BaseServicio_Reporte_Tecnico_Rth
{
    public function setUp() 
    {
		
	$this->actAs('Timestampable');
	$this->actAs('SoftDelete');
		
	$this->hasMany('Servicio_Reporte_Tecnico_Rth_Adjunto', array(
            'local' => 'id',
            'foreign' => 'servicio_reporte_tecnico_rth_id',
            ));
		
    }
	
    public function get_all()
    {
	$query = Doctrine_Query::create();
	$query->from(get_class($this) .' SERVICIO_REPORTE_TECNICO_RTH ');
	$query->leftJoin('SERVICIO_REPORTE_TECNICO_RTH.Servicio_Reporte_Tecnico_Rth_Adjunto SERVICIO_REPORTE_TECNICO_RTH_ADJUNTO ');
	$query->where("1 = 1");
	return $query;
    }
}