<?php

/**
 * Servicio_Boletin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Servicio_Boletin.php 98 2012-08-02 19:31:55Z mprado $
 */
class Servicio_Boletin extends BaseServicio_Boletin
{
    public function setUp() {
		
	$this->actAs('Timestampable');
	$this->actAs('SoftDelete');
		
	$this->hasOne('Auto_Modelo', array(
            'local' => 'auto_modelo_id',
            'foreign' => 'id'
            ));
		
	$this->hasOne('Servicio_Boletin_Categoria', array(
            'local' => 'servicio_boletin_categoria_id',
            'foreign' => 'id'
            ));
		
	$this->hasMany('Servicio_Boletin_Adjunto', array(
            'local' => 'id',
            'foreign' => 'servicio_boletin_id',
            ));
		
    }
	
    public function get_all()
    {
        $query = Doctrine_Query::create();
	$query->from(get_class($this) .' SERVICIO_BOLETIN ');
	$query->leftJoin('SERVICIO_BOLETIN.Auto_Modelo AUTO_MODELO ');
	$query->leftJoin('SERVICIO_BOLETIN.Servicio_Boletin_Categoria SERVICIO_BOLETIN_CATEGORIA ');
	$query->leftJoin('SERVICIO_BOLETIN.Servicio_Boletin_Adjunto SERVICIO_BOLETIN_ADJUNTO ');
	$query->where("1 = 1");
	return $query;
    }
}