<?php

/**
 * Servicio_Circular_Categoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Servicio_Circular_Categoria.php 98 2012-08-02 19:31:55Z mprado $
 */
class Servicio_Circular_Categoria extends BaseServicio_Circular_Categoria
{
    public function setUp() {
		
	$this->actAs('Timestampable');
	$this->actAs('SoftDelete');
		
	$this->hasMany('Servicio_Circular', array(
            'local' => 'id',
            'foreign' => 'servicio_circular_categoria_id',
            ));		
    }
	
    public function get_all()
    {
	$query = Doctrine_Query::create();
	$query->from(get_class($this) . ' SERVICIO_CIRCULAR_CATEGORIA ');
	$query->where("1 = 1");
	return $query;
    }
}