<?php

/**
 * Servicio_Manuales_Guias
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Servicio_Manuales_Guias.php 98 2012-08-02 19:31:55Z mprado $
 */
class Servicio_Manuales_Guias extends BaseServicio_Manuales_Guias
{
    public function setUp() {
		
	$this->actAs('Timestampable');
	$this->actAs('SoftDelete');
		
	$this->hasMany('Servicio_Manuales_Guias_Adjunto', array(
            'local' => 'id',
            'foreign' => 'servicio_manuales_guias_id',
            ));		
    }
	
    public function get_all()
    {
	$query = Doctrine_Query::create();
	$query->from(get_class($this) .' SERVICIO_MANUALES_GUIAS ');
	$query->leftJoin('SERVICIO_MANUALES_GUIAS.Servicio_Manuales_Guias_Adjunto SERVICIO_MANUALES_GUIAS_ADJUNTO ');
	$query->where("1 = 1");
	return $query;
    }
}