<?php

/**
 * Sucursal_Imagen
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Sucursal_Imagen.php 213 2012-09-17 13:36:03Z mprado $
 */
class Sucursal_Imagen extends BaseSucursal_Imagen
{
    
    public function setUp() {
	
        $this->actAs('Timestampable');

        $this->hasOne('Sucursal', array(
            'local' => 'sucursal_id',
            'foreign' => 'id'
        ));

    }

    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this));
        $query->where("1 = 1");
        return $query;
    }

}