<?php

/**
 * Sucursal_Servicio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Sucursal_Servicio.php 97 2012-08-01 21:57:04Z mprado $
 */
class Sucursal_Servicio extends BaseSucursal_Servicio
{
    public function setUp() {
		
        $this->actAs('Timestampable');
		
	$this->hasMany('Sucursal_Servicio_Imagen', array(
            'local' => 'id',
            'foreign' => 'sucursal_servicio_id',
            ));
		
	$this->hasOne('Sucursal', array(
            'local' => 'sucursal_id',
            'foreign' => 'id'
            ));
		
	$this->hasOne('Provincia', array(
            'local' => 'provincia_id',
            'foreign' => 'id'
            ));
		
	$this->hasOne('Ciudad', array(
            'local' => 'ciudad_id',
            'foreign' => 'id'
            ));
		
	$this->hasOne('Backend_Estado', array(
            'local' => 'backend_estado_id',
            'foreign' => 'id'
            ));
    }

    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this) .' SUCURSAL_SERVICIO ');
        $query->where("1 = 1");

        $query->leftJoin('SUCURSAL_SERVICIO.Sucursal SUCURSAL ');
        $query->leftJoin('SUCURSAL_SERVICIO.Backend_Estado BACKEND_ESTADO ');
        $query->leftJoin('SUCURSAL_SERVICIO.Provincia PROVINCIA ');
        $query->leftJoin('SUCURSAL_SERVICIO.Ciudad CIUDAD ');
        return $query;
    }	
	
}