<?php

/**
 * Sucursal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Sucursal.php 97 2012-08-01 21:57:04Z mprado $
 */
class Sucursal extends BaseSucursal
{
    public function setUp() {
		
	$this->actAs('Timestampable');
	
		
	$this->hasMany('Sucursal_Imagen', array(
                'local' => 'id',
                'foreign' => 'sucursal_id',
                ));
		
        $this->hasMany('Sucursal_Valor_Frt', array(
                'local' => 'id',
                'foreign' => 'sucursal_id',
                ));
		
	$this->hasMany('Unidad', array(
                'local' => 'id',
                'foreign' => 'sucursal_id'
                ));
		
        $this->hasMany('Usado', array(
                'local' => 'id',
                'foreign' => 'sucursal_id'
                ));
		
	$this->hasMany('Trafico_Pilot_Legend', array(
                'local' => 'id',
                'foreign' => 'sucursal_id'
                ));
		
	$this->hasOne('Empresa', array(
                'local' => 'empresa_id',
                'foreign' => 'id'
                ));
		
	$this->hasOne('Provincia', array(
                'local' => 'provincia_id',
                'foreign' => 'id'
                ));
		
	$this->hasOne('Ciudad', array(
                'local' => 'ciudad_id',
                'foreign' => 'id'
                ));
		
	$this->hasMany('Admin', array(
                'local' => 'id',
                'foreign' => 'sucursal_id'
                ));
		
	$this->hasMany('Tarjeta_Garantia', array(
                'local' => 'id',
                'foreign' => 'sucursal_id'
                ));
		
	$this->hasMany('Tsi', array(
                'local' => 'id',
                'foreign' => 'sucursal_id'
                ));
		
	$this->hasMany('Cliente_Sucursal', array(
                'local' => 'id',
                'foreign' => 'sucursal_id'
                ));
		
	$this->hasMany('Libro_Servicio', array(
                'local' => 'id',
                'foreign' => 'sucursal_id'
                ));
		
		
	$this->hasOne('Backend_Estado', array(
                'local' => 'backend_estado_id',
                'foreign' => 'id'
                ));
		
        $this->hasOne('Backend_Estado as Reporte_Usados', array(
                'local' => 'sucursal_field_reporte_usados',
                'foreign' => 'id'
                ));
		
        $this->hasMany('Admin as Many_Admin', array(
                'refClass' => 'Admin_M_Sucursal',
                'local' => 'sucursal_id',
                'foreign' => 'admin_id',
                ));
		
	$this->hasMany('Sucursal_Servicio', array(
                'local' => 'id',
                'foreign' => 'sucursal_id'
                ));
		
	$this->hasMany('Lineamiento_Comercial', array(
                'local' => 'id',
                'foreign' => 'sucursal_id'
                ));		
    }
	
    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this) .' SUCURSAL ');
        $query->where("1 = 1");

        $query->leftJoin('SUCURSAL.Empresa E ');
        $query->leftJoin('SUCURSAL.Backend_Estado BE ');
        $query->leftJoin('SUCURSAL.Provincia P ');
        $query->leftJoin('SUCURSAL.Ciudad C ');
        $query->leftJoin('SUCURSAL.Sucursal_Valor_Frt SUCURSAL_VALOR_FRT ');
        return $query;
    }
	
}