<?php

/**
 * Tarjeta_Garantia_Estado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Tarjeta_Garantia_Estado.php 97 2012-08-01 21:57:04Z mprado $
 */
class Tarjeta_Garantia_Estado extends BaseTarjeta_Garantia_Estado
{
    public function setUp() {
		
	$this->actAs('Timestampable');
	$this->actAs('SoftDelete');
		
	$this->hasMany('Tarjeta_Garantia', array(
            'local' => 'id',
            'foreign' => 'tarjeta_garantia_estado_id',
            ));	
		
	}
	
	public function get_all()
	{
            $query = Doctrine_Query::create();
            $query->from(get_class($this));
            $query->where("1 = 1");
            return $query;
	}
}