<?php

/**
 * Tarjeta_Garantia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Tarjeta_Garantia.php 721 2013-01-28 22:36:23Z slopez $
 */
class Tarjeta_Garantia extends BaseTarjeta_Garantia
{
    public function setUp() { 
	
        $this->actAs('Timestampable');
		
	$this->hasOne('Sucursal', array(
            'local' => 'sucursal_id',
            'foreign' => 'id'
            ));
        
	$this->hasOne('Admin as Admin_Vende', array(
            'local' => 'tarjeta_garantia_field_admin_vende_id',
            'foreign' => 'id'
            ));
        
	$this->hasOne('Unidad', array(
            'local' => 'unidad_id',
            'foreign' => 'id'
            ));
        
	$this->hasOne('Admin as Admin_Alta', array(
            'local' => 'tarjeta_garantia_field_admin_alta_id',
            'foreign' => 'id'
            ));
        
	$this->hasOne('Admin as Admin_Modifica', array(
            'local' => 'tarjeta_garantia_field_admin_modifica_id',
            'foreign' => 'id'
            ));
	
        $this->hasOne('Admin as Admin_Rechaza', array(
            'local' => 'tarjeta_garantia_field_admin_rechaza_id',
            'foreign' => 'id'
            ));
	
        $this->hasOne('Tarjeta_Garantia_Estado', array(
            'local' => 'tarjeta_garantia_estado_id',
            'foreign' => 'id'
            ));
		
	$this->hasMany('Cliente as Many_Cliente', array(
                'refClass' => 'Tarjeta_Garantia_M_Cliente',
                'local' => 'tarjeta_garantia_id',
                'foreign' => 'cliente_id'
            ));
		
	$this->hasOne('Encuesta_Nos', array(
            'local' => 'id',
            'foreign' => 'tarjeta_garantia_id'
            ));
		
		
	$this->hasMany('Encuesta_Nos', array(
            'local' => 'id',
            'foreign' => 'tarjeta_garantia_id'
            ));
    }
	
	
	public function get_grid()
	{
		$q = Doctrine_Query::create();
		$q->select(	'
						TARJETA_GARANTIA.id,
						UNIDAD.unidad_field_vin,
						UNIDAD.unidad_field_unidad,
						UNIDAD.unidad_field_motor,
						TARJETA_GARANTIA.tarjeta_garantia_field_fecha_entrega,
						SUCURSAL.sucursal_field_desc,
						UNIDAD.unidad_field_patente,
						UNIDAD_ESTADO_GARANTIA.unidad_estado_garantia_field_desc,
						MANY_UNIDAD_CODIGO_INTERNO.unidad_codigo_interno_field_desc,
						MANY_CLIENTE.id,
						MANY_CLIENTE_CODIGO_INTERNO.id,
						MANY_CLIENTE_CODIGO_INTERNO.cliente_codigo_interno_field_desc,
						TARJETA_GARANTIA_ESTADO.tarjeta_garantia_estado_field_desc,
						CLIENTE_SUCURSAL.cliente_sucursal_field_razon_social,
						CLIENTE_SUCURSAL.cliente_sucursal_field_nombre,
						CLIENTE_SUCURSAL.cliente_sucursal_field_apellido,
						DOCUMENTO_TIPO.documento_tipo_field_desc,
						CLIENTE_SUCURSAL.cliente_sucursal_field_email,
						MANY_CLIENTE.cliente_field_numero_documento,
						TARJETA_GARANTIA.tarjeta_garantia_field_fechahora_alta
						
		 ');
       $q->from('Tarjeta_Garantia TARJETA_GARANTIA');
	   $q->leftJoin('TARJETA_GARANTIA.Sucursal SUCURSAL ');
	   $q->leftJoin('TARJETA_GARANTIA.Unidad UNIDAD ');
	   $q->leftJoin('UNIDAD.Unidad_Estado_Garantia UNIDAD_ESTADO_GARANTIA');
	   $q->leftJoin('UNIDAD.Many_Unidad_Codigo_Interno MANY_UNIDAD_CODIGO_INTERNO ');
	   $q->leftJoin('TARJETA_GARANTIA.Many_Cliente MANY_CLIENTE ');
	   $q->leftJoin('MANY_CLIENTE.Many_Cliente_Codigo_Interno MANY_CLIENTE_CODIGO_INTERNO ');
	   $q->leftJoin('MANY_CLIENTE.Cliente_Sucursal CLIENTE_SUCURSAL ');
	   $q->leftJoin('MANY_CLIENTE.Documento_Tipo DOCUMENTO_TIPO ');
	   $q->leftJoin('TARJETA_GARANTIA.Tarjeta_Garantia_Estado TARJETA_GARANTIA_ESTADO ');
	  
	   
	   
	   $q->where("SUCURSAL.id = CLIENTE_SUCURSAL.sucursal_id");
	   
	   RETURN $q;
	}	
	
	
	
    public function get_all()
    {

        $query = Doctrine_Query::create();
        $query->from(get_class($this) . ' TARJETA_GARANTIA ');
        $query->where("1 = 1");
        //$query->addWhere("CS.sucursal_id=TARJETA_GARANTIA.sucursal_id"); WTF!
        $query->leftJoin('TARJETA_GARANTIA.Sucursal S ');
        $query->leftJoin('TARJETA_GARANTIA.Admin_Alta AALTA ');
        $query->leftJoin('TARJETA_GARANTIA.Admin_Modifica AMODIFICA ');
        $query->leftJoin('TARJETA_GARANTIA.Admin_Vende AVENDE ');
        $query->leftJoin('TARJETA_GARANTIA.Unidad UNIDAD ');
        $query->leftJoin('UNIDAD.Vin_Procedencia_Ktype VP ');
        $query->leftJoin('UNIDAD.Many_Unidad_Codigo_Interno UCI ');
        $query->leftJoin('UNIDAD.Auto_Version AV ');
        $query->leftJoin('UNIDAD.Unidad_Color_Interior CI ');
        $query->leftJoin('UNIDAD.Unidad_Color_Exterior CE ');
        $query->leftJoin('AV.Auto_Modelo AM ');
        $query->leftJoin('UNIDAD.Auto_Transmision AT ');
        $query->leftJoin('UNIDAD.Auto_Anio AA ');
        $query->leftJoin('UNIDAD.Auto_Puerta_Cantidad PC ');
        $query->leftJoin('UNIDAD.Unidad_Estado_Garantia UEG ');

        $query->leftJoin('TARJETA_GARANTIA.Tarjeta_Garantia_Estado E ');
        $query->leftJoin('TARJETA_GARANTIA.Many_Cliente MANY_CLIENTE ');
        $query->leftJoin('MANY_CLIENTE.Many_Cliente_Codigo_Interno MANY_CLIENTE_CODIGO_INTERNO ');
        $query->leftJoin('MANY_CLIENTE.Cliente_Sucursal CLIENTE_SUCURSAL ');
        $query->leftJoin('CLIENTE_SUCURSAL.Tratamiento T ');
        $query->leftJoin('CLIENTE_SUCURSAL.Sexo SE ');
        $query->leftJoin('CLIENTE_SUCURSAL.Pais PA ');
        $query->leftJoin('CLIENTE_SUCURSAL.Ciudad C ');
        $query->leftJoin('CLIENTE_SUCURSAL.Provincia P ');
        $query->leftJoin('MANY_CLIENTE.Documento_Tipo DT ');
        $query->leftJoin('MANY_CLIENTE.Cliente_Conformidad CC ');
        $query->addWhere("S.id = CLIENTE_SUCURSAL.sucursal_id");
        //$query->groupBy('TARJETA_GARANTIA.id');
        //echo $query->getSqlQuery();
        return $query;
    }

    public function get_propietario_original($vin = FALSE, $unidad = FALSE)
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this) . ' TARJETA_GARANTIA ');
		$query->leftJoin('TARJETA_GARANTIA.Unidad UNIDAD ');
		$query->leftJoin('TARJETA_GARANTIA.Many_Cliente MANY_CLIENTE ');
		$query->leftJoin('MANY_CLIENTE.Cliente_Sucursal CLIENTE_SUCURSAL ');
        $query->addWhere('unidad_field_unidad = ?',	$unidad);
        $query->addWhere('unidad_field_vin = ?',	$vin);
        $query->addWhere('tarjeta_garantia_estado_id != ?',	9); //no esta rechazada
        $query->addWhere('tarjeta_garantia_estado_id != ?',	3); //no esta esperando aprobacion
        $query->orderBy('tarjeta_garantia_field_fecha_entrega ASC');
        $query->limit(1);
        return $query;
    }
	
	
	
	public function postInsert(Doctrine_Event $event)
    {
        $invoker = $event->getInvoker();
		$q = Doctrine_Query::create();
		$q->from('Tarjeta_Garantia Tarjeta_Garantia');
		$q->where('Tarjeta_Garantia.unidad_id = ?',$invoker->unidad_id);
		$q->whereIn('Tarjeta_Garantia.tarjeta_garantia_estado_id ',array(1,2));
		$q->orderBy('tarjeta_garantia_field_fecha_entrega ASC');
		if($q->count() > 0)
		{
			
			$row = $q->fetchOne(array(),Doctrine_Core::HYDRATE_ARRAY);
			$fecha = $row['tarjeta_garantia_field_fecha_entrega'];
		}
		else
		{
			$fecha = NULL;
		}
		
		$q = Doctrine_Query::create()
        ->update('Unidad')
        ->set('unidad_field_fecha_entrega','?', $fecha)
        ->where('id = ?',$invoker->unidad_id)->execute();
		
    }
	
	
    public function postUpdate(Doctrine_Event $event)
    {
        $invoker = $event->getInvoker();
		$q = Doctrine_Query::create();
		$q->from('Tarjeta_Garantia Tarjeta_Garantia');
		$q->where('Tarjeta_Garantia.unidad_id = ?',$invoker->unidad_id);
		$q->whereIn('Tarjeta_Garantia.tarjeta_garantia_estado_id ',array(1,2));
		$q->orderBy('tarjeta_garantia_field_fecha_entrega ASC');
		if($q->count() > 0)
		{
			
			$row = $q->fetchOne(array(),Doctrine_Core::HYDRATE_ARRAY);
			$fecha = $row['tarjeta_garantia_field_fecha_entrega'];
		}
		else
		{
			$fecha = NULL;
		}
		
		$q = Doctrine_Query::create()
        ->update('Unidad')
        ->set('unidad_field_fecha_entrega','?', $fecha)
        ->where('id = ?',$invoker->unidad_id)->execute();
		
    }
	
	
	
	
	
}