<?php

/**
 * Tsi
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Tsi.php 854 2013-03-14 04:56:18Z slopez $
 */
class Tsi extends BaseTsi
{
    public function setUp() { 
	parent::setUp();
	$this->actAs('Timestampable');		
		
	$this->hasOne('Sucursal', array(
            'local' => 'sucursal_id',
            'foreign' => 'id'
            ));
        
	$this->hasOne('Unidad', array(
            'local' => 'unidad_id',
            'foreign' => 'id'
            ));
	
        $this->hasOne('Admin as Recepcionista', array(
            'local' => 'tsi_field_admin_recepcionista_id',
            'foreign' => 'id'
            ));
	
        $this->hasOne('Admin as Tecnico', array(
            'local' => 'tsi_field_admin_tecnico_id',
            'foreign' => 'id'
            ));
		
	$this->hasOne('Admin as Admin_Alta', array(
            'local' => 'tsi_field_admin_alta_id',
            'foreign' => 'id'
            ));
        
	$this->hasOne('Admin as Admin_Modifica', array(
            'local' => 'tsi_field_admin_modifica_id',
            'foreign' => 'id'
            ));
	
        $this->hasOne('Admin as Admin_Rechaza', array(
            'local' => 'tsi_field_admin_rechaza_id',
            'foreign' => 'id'
            ));
	
        $this->hasOne('Tsi_Tipo_Mantenimiento', array(
            'local' => 'tsi_tipo_mantenimiento_id',
            'foreign' => 'id'
            ));
            
	$this->hasOne('Tsi_Motivo_Reparacion', array(
            'local' => 'tsi_motivo_reparacion_id',
            'foreign' => 'id'
            ));
		
	$this->hasOne('Cliente', array(
            'local' => 'cliente_id',
            'foreign' => 'id'
            ));
		
	$this->hasOne('Tsi_Estado', array(
            'local' => 'tsi_estado_id',
            'foreign' => 'id'
            ));
		
	$this->hasMany('Tsi_Tipo_Servicio as Many_Tsi_Tipo_Servicio', array(
                'refClass' => 'Tsi_M_Tsi_Tipo_Servicio',
                'local' => 'tsi_id',
                'foreign' => 'tsi_tipo_servicio_id'
            ));
		
	$this->hasOne('Tsi_Encuesta_Satisfaccion', array(
            'local' => 'id',
            'foreign' => 'tsi_id'
            ));
        
	$this->hasOne('Tsi_Encuesta_Seguimiento', array(
            'local' => 'id',
            'foreign' => 'tsi_id'
            ));
		
	$this->hasMany('Reclamo_Garantia', array(
            'local' => 'id',
            'foreign' => 'tsi_id'
            ));		
    }  
	
	
	public function get_grid()
	{
		$q = Doctrine_Query::create();
		$q->select(	'
						TSI.id,
						SUCURSAL.sucursal_field_desc,
						TSI.tsi_field_fecha_de_egreso,
						UNIDAD.unidad_field_unidad,
						UNIDAD.unidad_field_vin,
						UNIDAD.unidad_field_motor,
						UNIDAD.unidad_field_patente,
						UNIDAD.unidad_field_material_sap,
						TSI_TIPO_SERVICIO.tsi_tipo_servicio_field_desc,
						TSI.tsi_field_kilometros,
						CLIENTE.id,
						CLIENTE_SUCURSAL.id,
						CLIENTE_SUCURSAL.cliente_sucursal_field_nombre,
						CLIENTE_SUCURSAL.cliente_sucursal_field_apellido,
						CLIENTE_SUCURSAL.cliente_sucursal_field_razon_social,
						TSI.tsi_field_fechahora_alta
						
						
		 ');
		$q->from('Tsi TSI');
		$q->leftJoin('TSI.Sucursal SUCURSAL ');
		$q->leftJoin('TSI.Unidad UNIDAD ');
		$q->leftJoin('TSI.Many_Tsi_Tipo_Servicio TSI_TIPO_SERVICIO ');
		$q->leftJoin('TSI.Cliente CLIENTE ');
		$q->leftJoin('CLIENTE.Cliente_Sucursal CLIENTE_SUCURSAL ON CLIENTE.id = CLIENTE_SUCURSAL.cliente_id AND CLIENTE_SUCURSAL.sucursal_id = TSI.sucursal_id');
		$q->where('1 = 1');
		RETURN $q;
	}
	
	
    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this) . ' TSI ');
        $query->leftJoin('TSI.Sucursal S ');

        $query->leftJoin('TSI.Tsi_Tipo_Mantenimiento TSI_TIPO_MANTENIMIENTO ');
        $query->leftJoin('TSI.Tsi_Motivo_Reparacion TSI_MOTIVO_REPARACION ');
        $query->leftJoin('TSI.Tecnico TECNICO ');
        $query->leftJoin('TSI.Recepcionista RECEPCIONISTA ');
        $query->leftJoin('TSI.Tsi_Estado TSI_ESTADO ');
        $query->leftJoin('TSI.Admin_Alta ADMIN_ALTA ');
        $query->leftJoin('TSI.Admin_Modifica ADMIN_MODIFICA ');
        //--[unidad]
        $query->leftJoin('TSI.Unidad UNIDAD ');
        $query->leftJoin('UNIDAD.Vin_Procedencia_Ktype VP ');
        $query->leftJoin('UNIDAD.Many_Unidad_Codigo_Interno UCI ');
        $query->leftJoin('UNIDAD.Unidad_Color_Interior CI ');
        $query->leftJoin('UNIDAD.Unidad_Color_Exterior CE ');
        $query->leftJoin('UNIDAD.Auto_Transmision AT ');
        $query->leftJoin('UNIDAD.Auto_Anio AA ');
        $query->leftJoin('UNIDAD.Auto_Puerta_Cantidad PC ');
        $query->leftJoin('UNIDAD.Auto_Version AUTO_VERSION ');
        $query->leftJoin('AUTO_VERSION.Auto_Modelo AM ');
        //--[fin unidad]
        $query->leftJoin('UNIDAD.Sucursal SUCURSAL ');

        $query->leftJoin('TSI.Many_Tsi_Tipo_Servicio TSI_TIPO_SERVICIO ');
		$query->leftJoin('TSI.Tsi_Promocion TSI_PROMOCION ');

        //--[cliente]
        $query->leftJoin('TSI.Cliente CLIENTE ');
		$query->leftJoin('CLIENTE.Many_Cliente_Codigo_Interno MANY_CLIENTE_CODIGO_INTERNO ');
        $query->leftJoin('CLIENTE.Documento_Tipo DT ');
        $query->leftJoin('CLIENTE.Cliente_Conformidad CC ');
        $query->leftJoin('CLIENTE.Cliente_Sucursal CLIENTE_SUCURSAL ON CLIENTE.id = CLIENTE_SUCURSAL.cliente_id AND CLIENTE_SUCURSAL.sucursal_id = TSI.sucursal_id');
        $query->leftJoin('CLIENTE_SUCURSAL.Tratamiento T ');
        $query->leftJoin('CLIENTE_SUCURSAL.Sexo SE ');
        $query->leftJoin('CLIENTE_SUCURSAL.Pais PA ');
        $query->leftJoin('CLIENTE_SUCURSAL.Ciudad C ');
        $query->leftJoin('CLIENTE_SUCURSAL.Provincia P ');

        $query->where("1 = 1");
        return $query;
    }
	
	
	public function get_export()
    {
        $query = Doctrine_Query::create();
		$query->select('		TSI.id,
								TSI.tsi_field_fecha_de_egreso,
								TSI.tsi_field_fechahora_alta,
								TSI.tsi_field_orden_de_reparacion,
								TSI.tsi_field_kilometros
							
		
		');
		$query->addSelect('		UNIDAD.unidad_field_unidad,
								UNIDAD.unidad_field_vin,
								UNIDAD.unidad_field_motor,
								UNIDAD.unidad_field_patente,
								UNIDAD.unidad_field_codigo_de_llave,
								UNIDAD.unidad_field_codigo_de_radio,
								UNIDAD.unidad_field_fecha_entrega,
								
								
		');
		$query->addSelect('		AM.auto_modelo_field_desc');
		$query->addSelect('		AUTO_VERSION.auto_version_field_desc');
		$query->addSelect('		AT.auto_transmision_field_desc');
		$query->addSelect('		AA.auto_anio_field_desc');
		$query->addSelect('		S.sucursal_field_desc');
		
		$query->addSelect('		TSI_TIPO_SERVICIO.tsi_tipo_servicio_field_desc');
		$query->addSelect('		TSI_TIPO_MANTENIMIENTO.tsi_tipo_mantenimiento_field_desc');
		$query->addSelect('		TSI_MOTIVO_REPARACION.tsi_motivo_reparacion_field_desc');
		$query->addSelect('		TSI_PROMOCION.tsi_promocion_field_desc');
		
		$query->addSelect('		RECEPCIONISTA.admin_field_nombre,
								RECEPCIONISTA.admin_field_apellido
								
		');
		
		$query->addSelect('		TECNICO.admin_field_nombre,
								TECNICO.admin_field_apellido
								
		');
		
		$query->addSelect('		T.tratamiento_field_desc');
		
		$query->addSelect('		CLIENTE_SUCURSAL.cliente_sucursal_field_razon_social,
								CLIENTE_SUCURSAL.cliente_sucursal_field_nombre,
								CLIENTE_SUCURSAL.cliente_sucursal_field_apellido,
								CLIENTE_SUCURSAL.cliente_sucursal_field_direccion_calle,
								CLIENTE_SUCURSAL.cliente_sucursal_field_direccion_numero,
								CLIENTE_SUCURSAL.cliente_sucursal_field_direccion_piso,
								CLIENTE_SUCURSAL.cliente_sucursal_field_direccion_depto,
								CLIENTE_SUCURSAL.cliente_sucursal_field_direccion_codigo_postal,
								CLIENTE_SUCURSAL.cliente_sucursal_field_telefono_particular_codigo,
								CLIENTE_SUCURSAL.cliente_sucursal_field_telefono_particular_numero,
								CLIENTE_SUCURSAL.cliente_sucursal_field_telefono_laboral_codigo,
								CLIENTE_SUCURSAL.cliente_sucursal_field_telefono_laboral_numero,
								CLIENTE_SUCURSAL.cliente_sucursal_field_telefono_movil_codigo,
								CLIENTE_SUCURSAL.cliente_sucursal_field_telefono_movil_numero,
								CLIENTE_SUCURSAL.cliente_sucursal_field_fax_codigo,
								CLIENTE_SUCURSAL.cliente_sucursal_field_fax_numero,
								CLIENTE_SUCURSAL.cliente_sucursal_field_email,
								CLIENTE_SUCURSAL.cliente_sucursal_field_fecha_nacimiento
								
		');
		
		$query->addSelect('		CC.cliente_conformidad_field_desc');
		
		$query->addSelect('		DT.documento_tipo_field_desc');
		
		$query->addSelect('		CLIENTE.cliente_field_numero_documento');
		
		$query->addSelect('		P.provincia_field_desc');
		
		$query->addSelect('		C.ciudad_field_desc');
		
		$query->addSelect('		SE.sexo_field_desc');
		
		$query->addSelect('		ADMIN_ALTA.admin_field_usuario');
		
		$query->addSelect('		UCI.unidad_codigo_interno_field_desc');
		
		
		
		
        $query->from(get_class($this) . ' TSI ');
        $query->leftJoin('TSI.Sucursal S ');

        $query->leftJoin('TSI.Tsi_Tipo_Mantenimiento TSI_TIPO_MANTENIMIENTO ');
        $query->leftJoin('TSI.Tsi_Motivo_Reparacion TSI_MOTIVO_REPARACION ');
        $query->leftJoin('TSI.Tecnico TECNICO ');
        $query->leftJoin('TSI.Recepcionista RECEPCIONISTA ');
        $query->leftJoin('TSI.Tsi_Estado TSI_ESTADO ');
        $query->leftJoin('TSI.Admin_Alta ADMIN_ALTA ');
        $query->leftJoin('TSI.Admin_Modifica ADMIN_MODIFICA ');
        //--[unidad]
        $query->leftJoin('TSI.Unidad UNIDAD ');
        $query->leftJoin('UNIDAD.Vin_Procedencia_Ktype VP ');
        $query->leftJoin('UNIDAD.Many_Unidad_Codigo_Interno UCI ');
        $query->leftJoin('UNIDAD.Unidad_Color_Interior CI ');
        $query->leftJoin('UNIDAD.Unidad_Color_Exterior CE ');
        $query->leftJoin('UNIDAD.Auto_Transmision AT ');
        $query->leftJoin('UNIDAD.Auto_Anio AA ');
        $query->leftJoin('UNIDAD.Auto_Puerta_Cantidad PC ');
        $query->leftJoin('UNIDAD.Auto_Version AUTO_VERSION ');
        $query->leftJoin('AUTO_VERSION.Auto_Modelo AM ');
        //--[fin unidad]
        $query->leftJoin('UNIDAD.Sucursal SUCURSAL ');

        $query->leftJoin('TSI.Many_Tsi_Tipo_Servicio TSI_TIPO_SERVICIO ');
		$query->leftJoin('TSI.Tsi_Promocion TSI_PROMOCION ');

        //--[cliente]
        $query->leftJoin('TSI.Cliente CLIENTE ');
		$query->leftJoin('CLIENTE.Many_Cliente_Codigo_Interno MANY_CLIENTE_CODIGO_INTERNO ');
        $query->leftJoin('CLIENTE.Documento_Tipo DT ');
        $query->leftJoin('CLIENTE.Cliente_Conformidad CC ');
        $query->leftJoin('CLIENTE.Cliente_Sucursal CLIENTE_SUCURSAL ON CLIENTE.id = CLIENTE_SUCURSAL.cliente_id AND CLIENTE_SUCURSAL.sucursal_id = TSI.sucursal_id');
        $query->leftJoin('CLIENTE_SUCURSAL.Tratamiento T ');
        $query->leftJoin('CLIENTE_SUCURSAL.Sexo SE ');
        $query->leftJoin('CLIENTE_SUCURSAL.Pais PA ');
        $query->leftJoin('CLIENTE_SUCURSAL.Ciudad C ');
        $query->leftJoin('CLIENTE_SUCURSAL.Provincia P ');

        $query->where("1 = 1");
        return $query;
    }
	
	
	
	public function postUpdate(Doctrine_Event $event)
    {
        $invoker = $event->getInvoker();
		$q = Doctrine_Query::create();
		$q->from('Tsi Tsi');
		$q->where('Tsi.unidad_id = ?',$invoker->unidad_id);
		$q->whereIn('Tsi.tsi_estado_id ',array(2));
		$q->orderBy('Tsi.id DESC');
		if($q->count() > 0)
		{
			
			$row = $q->fetchOne(array(),Doctrine_Core::HYDRATE_ARRAY);
			$kms = $row['tsi_field_kilometros'];
		}
		else
		{
			$kms = NULL;
		}
		
		$q = Doctrine_Query::create()
        ->update('Unidad')
        ->set('unidad_field_kilometros','?', $kms)
        ->where('id = ?',$invoker->unidad_id)->execute();
		
    }
	
	public function postInsert(Doctrine_Event $event)
    {
        $invoker = $event->getInvoker();
		$q = Doctrine_Query::create();
		$q->from('Tsi Tsi');
		$q->where('Tsi.unidad_id = ?',$invoker->unidad_id);
		$q->whereIn('Tsi.tsi_estado_id ',array(2));
		$q->orderBy('Tsi.id DESC');
		if($q->count() > 0)
		{
			
			$row = $q->fetchOne(array(),Doctrine_Core::HYDRATE_ARRAY);
			$kms = $row['tsi_field_kilometros'];
		}
		else
		{
			$kms = NULL;
		}
		
		$q = Doctrine_Query::create()
        ->update('Unidad')
        ->set('unidad_field_kilometros','?', $kms)
        ->where('id = ?',$invoker->unidad_id)->execute();
		
    }
	
	
	
	
}