<?php

/**
 * Tsi_Mailing_Encuesta_Satisfaccion_Clientes_Estado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tsi_Mailing_Encuesta_Satisfaccion_Clientes_Estado extends BaseTsi_Mailing_Encuesta_Satisfaccion_Clientes_Estado
{
    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this) . ' TSI_MESCE ');        
        $query->where(" 1 = 1 ");
        return $query;
    }    
}