<?php

/**
 * Tsi_Mailing_Encuesta_Satisfaccion_Clientes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tsi_Mailing_Encuesta_Satisfaccion_Clientes extends BaseTsi_Mailing_Encuesta_Satisfaccion_Clientes
{
    
     public function setUp() {
		
	$this->actAs('Timestampable');
	$this->actAs('SoftDelete');
		
	$this->hasOne('Tsi_Mailing_Encuesta_Satisfaccion_Clientes_Estado', array(
            'local' => 'tsi_mailing_encuesta_satisfaccion_clientes_estado_id',
            'foreign' => 'id'
        ));
    }
    
    public function get_all()
     {
        $query = Doctrine_Query::create();
        $query->from(get_class($this) . ' TSI_MESC ');
        $query->leftJoin(' TSI_MESC.Tsi_Mailing_Encuesta_Satisfaccion_Clientes_Estado TSI_MESCE ');
        $query->where(" 1 = 1 ");
        return $query;
     }
}