<?php

/**
 * Tsi_Encuesta_Satisfaccion_Razon_Repetir_Servicio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Tsi_Encuesta_Satisfaccion_Razon_Repetir_Servicio.php 97 2012-08-01 21:57:04Z mprado $
 */
class Tsi_Encuesta_Satisfaccion_Razon_Repetir_Servicio extends BaseTsi_Encuesta_Satisfaccion_Razon_Repetir_Servicio
{
    public function setUp() { 
		
	$this->hasMany('Tsi_Encuesta_Satisfaccion', array(
            'local' => 'id',
            'foreign' => 'tsi_encuesta_satisfaccion_field_pregunta_06b'
            ));
		
		
	$this->actAs('Timestampable');     
        
    }
	
    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this) . ' TSI_ENCUESTA_SATISFACCION_RAZON_REPETIR_SERVICIO ');
        $query->where("1 = 1");
	return $query;
    }
	
}