<?php

/**
 * Tsi_Estado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Tsi_Estado.php 97 2012-08-01 21:57:04Z mprado $
 */
class Tsi_Estado extends BaseTsi_Estado
{
    public function setUp() {
		
        $this->actAs('Timestampable');
        $this->actAs('SoftDelete');

        $this->hasMany('Tsi', array(
            'local' => 'id',
            'foreign' => 'tsi_estado',
            ));		
    }

    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this));
        $query->where("1 = 1");
        return $query;
    }
}