<?php

/**
 * Tsi_Tipo_Servicio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Tsi_Tipo_Servicio.php 97 2012-08-01 21:57:04Z mprado $
 */
class Tsi_Tipo_Servicio extends BaseTsi_Tipo_Servicio
{
    public function setUp() {
		
	$this->actAs('Timestampable');
	$this->actAs('SoftDelete');
		
	$this->hasMany('Tsi as Many_Tsi', array(
                'refClass' => 'Tsi_M_Tsi_Tipo_Servicio',
                'local' => 'tsi_tipo_servicio_id',
                'foreign' => 'tsi_id'
            ));
    }
	
    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this));
        $query->where("1 = 1");
        return $query;
    }
}