<?php

/**
 * Tsi_Encuesta_Seguimiento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Tsi_Encuesta_Seguimiento.php 97 2012-08-01 21:57:04Z mprado $
 */
class Tsi_Encuesta_Seguimiento extends BaseTsi_Encuesta_Seguimiento
{
    public function setUp() { 
		
	$this->hasOne('Tsi', array(
            'local' => 'tsi_id',
            'foreign' => 'id'
            ));
		
	$this->hasOne('Tsi_Encuesta_Seguimiento_Estado', array(
            'local' => 'tsi_encuesta_seguimiento_estado_id',
            'foreign' => 'id'
            ));
		
	$this->hasOne('Admin as Admin_Alta', array(
            'local' => 'tsi_encuesta_seguimiento_field_admin_alta_id',
            'foreign' => 'id'
            ));
	$this->hasOne('Admin as Admin_Modifica', array(
            'local' => 'tsi_encuesta_seguimiento_field_admin_modifica_id',
            'foreign' => 'id'
            ));		
		
	$this->actAs('Timestampable');		
		
    }

    //-------------------------------------

    public function get_all()
    {

        $query = Doctrine_Query::create();
        $query->from(get_class($this) . ' TSI_ENCUESTA_SEGUIMIENTO ');
        $query->leftJoin('TSI_ENCUESTA_SEGUIMIENTO.Tsi_Encuesta_Seguimiento_Estado TSI_ENCUESTA_SEGIMIENTO_ESTADO ');
        $query->leftJoin('TSI_ENCUESTA_SEGUIMIENTO.Tsi TSI ');
        $query->leftJoin('TSI.Unidad UNIDAD ');
        $query->leftJoin('UNIDAD.Auto_Version AUTO_VERSION ');
        $query->leftJoin('AUTO_VERSION.Auto_Modelo AUTO_MODELO ');
        $query->leftJoin('TSI.Many_Tsi_Tipo_Servicio MANY_TSI_TIPO_SERVICIO ');
        $query->leftJoin('TSI.Cliente CLIENTE ');
        $query->leftJoin('TSI.Sucursal SUCURSAL ');
        $query->leftJoin('CLIENTE.Cliente_Sucursal CLIENTE_SUCURSAL ON CLIENTE.id = CLIENTE_SUCURSAL.cliente_id AND CLIENTE_SUCURSAL.sucursal_id = TSI.sucursal_id');
        $query->leftJoin('TSI_ENCUESTA_SEGUIMIENTO.Admin_Alta ADMIN_ALTA ');
        $query->leftJoin('TSI_ENCUESTA_SEGUIMIENTO.Admin_Modifica ADMIN_MODIFICA ');

        $query->where("1 = 1");

        return $query;
    }

}