<?php

/**
 * Tsi_Encuesta_Satisfaccion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Tsi_Encuesta_Satisfaccion.php 454 2012-11-21 07:03:36Z slopez $
 */
class Tsi_Encuesta_Satisfaccion extends BaseTsi_Encuesta_Satisfaccion
{
    public function setUp() { 
		
	$this->hasOne('Tsi', array(
            'local' => 'tsi_id',
            'foreign' => 'id'
            ));
		
	$this->hasOne('Tsi_Encuesta_Satisfaccion_Estado', array(
            'local' => 'tsi_encuesta_satisfaccion_estado_id',
            'foreign' => 'id'
            ));
		
	$this->hasOne('Admin as Admin_Alta', array(
            'local' => 'tsi_encuesta_satisfaccion_field_admin_alta_id',
            'foreign' => 'id'
            ));
	
        $this->hasOne('Admin as Admin_Modifica', array(
            'local' => 'tsi_encuesta_satisfaccion_field_admin_modifica_id',
            'foreign' => 'id'
            ));
		
	$this->hasOne('Tsi_Encuesta_Satisfaccion_Razon_Repetir_Servicio', array(
            'local' => 'tsi_encuesta_satisfaccion_field_pregunta_06b',
            'foreign' => 'id'
            ));
		
	$this->hasOne('Tsi_Encuesta_Satisfaccion_Visitas_Adicionales', array(
            'local' => 'id',
            'foreign' => 'tsi_encuesta_satisfaccion_field_pregunta_06b'
            ));		
		
	$this->actAs('Timestampable');		
		
    }

	public function postUpdate($event)
    {
	   $invoker = $event->getInvoker();
	   $this->crear_indices_honda($invoker->id);
    }
	
	public function postInsert($event)
    {
	   $invoker = $event->getInvoker();
	   $this->crear_indices_honda($invoker->id);
    }
	
    public function get_all()
    {

        $query = Doctrine_Query::create();
        $query->from(get_class($this) . ' TSI_ENCUESTA_SATISFACCION ');
        $query->leftJoin('TSI_ENCUESTA_SATISFACCION.Tsi_Encuesta_Satisfaccion_Estado TSI_ENCUESTA_SATISFACCION_ESTADO ');
        $query->leftJoin('TSI_ENCUESTA_SATISFACCION.Tsi TSI ');
        $query->leftJoin('TSI.Unidad UNIDAD ');
		$query->leftJoin('TSI.Tecnico TECNICO ');
		$query->leftJoin('TSI.Recepcionista RECEPCIONISTA ');
        $query->leftJoin('UNIDAD.Auto_Version AUTO_VERSION ');
		$query->leftJoin('UNIDAD.Auto_Anio AUTO_ANIO ');
		$query->leftJoin('UNIDAD.Auto_Transmision AUTO_TRANSMISION ');
		$query->leftJoin('UNIDAD.Many_Unidad_Codigo_Interno MANY_UNIDAD_CODIGO_INTERNO ');
        $query->leftJoin('AUTO_VERSION.Auto_Modelo AUTO_MODELO ');
        $query->leftJoin('TSI.Many_Tsi_Tipo_Servicio MANY_TSI_TIPO_SERVICIO ');
        $query->leftJoin('TSI.Cliente CLIENTE ');
		
		
		
		
		
		$query->leftJoin('CLIENTE.Documento_Tipo DOCUMENTO_TIPO ');
		$query->leftJoin('CLIENTE.Many_Cliente_Codigo_Interno MANY_CLIENTE_CODIGO_INTERNO ');
		$query->leftJoin('TSI.Sucursal SUCURSAL ');
        $query->leftJoin('CLIENTE.Cliente_Sucursal CLIENTE_SUCURSAL ON CLIENTE.id = CLIENTE_SUCURSAL.cliente_id AND CLIENTE_SUCURSAL.sucursal_id = TSI.sucursal_id');
		
		$query->leftJoin('CLIENTE_SUCURSAL.Provincia PROVINCIA ');
		$query->leftJoin('CLIENTE_SUCURSAL.Ciudad CIUDAD ');
		
        $query->leftJoin('TSI_ENCUESTA_SATISFACCION.Admin_Alta ADMIN_ALTA ');
        $query->leftJoin('TSI_ENCUESTA_SATISFACCION.Admin_Modifica ADMIN_MODIFICA ');

        $query->where("1 = 1");
		//$query->addWhere('CLIENTE_SUCURSAL.sucursal_id = TSI.sucursal_id');

        return $query;
    }
	
	public function get_report()
	{
		$query = Doctrine_Query::create();
		$query->select('TSI_ENCUESTA_SATISFACCION.*');
        $query->from(get_class($this) . ' TSI_ENCUESTA_SATISFACCION ');
        $query->leftJoin('TSI_ENCUESTA_SATISFACCION.Tsi_Encuesta_Satisfaccion_Estado TSI_ENCUESTA_SATISFACCION_ESTADO ');
        $query->leftJoin('TSI_ENCUESTA_SATISFACCION.Tsi TSI ');
        $query->leftJoin('TSI.Unidad UNIDAD ');
		
        $query->leftJoin('UNIDAD.Auto_Version AUTO_VERSION ');
		
        $query->leftJoin('AUTO_VERSION.Auto_Modelo AUTO_MODELO ');
		
        $query->where("1 = 1");
		//$query->addWhere('CLIENTE_SUCURSAL.sucursal_id = TSI.sucursal_id');

        return $query;
	}
	
	public function crear_indices_honda( $id )
	{
		$q = Doctrine_Query::create();
        $q->from(get_class($this) . ' TSI_ENCUESTA_SATISFACCION ');
		$q->addWhere('TSI_ENCUESTA_SATISFACCION.id = ?',$id);
		$encuesta = $q->fetchOne();
		if($encuesta)
		{
			
			$indice_capacidad = 0;
			$indice_interpersonal = 0;
			$indice_calidad = 0;
		
			//indice de capacidad....
			if
			(
				1==1 OR
				(
					$encuesta->tsi_encuesta_satisfaccion_field_pregunta_01a>0 AND
					$encuesta->tsi_encuesta_satisfaccion_field_pregunta_02a>0 AND
					$encuesta->tsi_encuesta_satisfaccion_field_pregunta_03a>0 AND
					$encuesta->tsi_encuesta_satisfaccion_field_pregunta_03b>0 AND
					$encuesta->tsi_encuesta_satisfaccion_field_pregunta_03c>0 AND
					$encuesta->tsi_encuesta_satisfaccion_field_pregunta_04a>0 AND
					$encuesta->tsi_encuesta_satisfaccion_field_pregunta_04b>0 AND
					$encuesta->tsi_encuesta_satisfaccion_field_pregunta_04e>0
				)
			)
			{
				if($encuesta->tsi_encuesta_satisfaccion_field_pregunta_01a>0)
					$indice_capacidad+=($encuesta->tsi_encuesta_satisfaccion_field_pregunta_01a-1) *(0.7*25);
				if($encuesta->tsi_encuesta_satisfaccion_field_pregunta_02a>0)
					$indice_capacidad+=($encuesta->tsi_encuesta_satisfaccion_field_pregunta_02a-1) *(1.4*25);
				if($encuesta->tsi_encuesta_satisfaccion_field_pregunta_03a>0)
					$indice_capacidad+=($encuesta->tsi_encuesta_satisfaccion_field_pregunta_03a-1) *(0.95*25);
				if($encuesta->tsi_encuesta_satisfaccion_field_pregunta_03b>0)
					$indice_capacidad+=($encuesta->tsi_encuesta_satisfaccion_field_pregunta_03b-1) *(0.55*25);
				if($encuesta->tsi_encuesta_satisfaccion_field_pregunta_03c>0)
					$indice_capacidad+=($encuesta->tsi_encuesta_satisfaccion_field_pregunta_03c-1) *(0.55*25);
				if($encuesta->tsi_encuesta_satisfaccion_field_pregunta_04a>0)
					$indice_capacidad+=($encuesta->tsi_encuesta_satisfaccion_field_pregunta_04a-1) *(0.8*25);
				if($encuesta->tsi_encuesta_satisfaccion_field_pregunta_04b>0)
					$indice_capacidad+=($encuesta->tsi_encuesta_satisfaccion_field_pregunta_04b-1) *(0.9*25);
				if($encuesta->tsi_encuesta_satisfaccion_field_pregunta_04e>0)
					$indice_capacidad+=($encuesta->tsi_encuesta_satisfaccion_field_pregunta_04e-1) *(0.95*25);	
			}
				
			
			$indice_capacidad= round(($indice_capacidad/680)*100,2);
			//indice de capacidad....
			
			if
			(
				1==1 OR
				(
					$encuesta->tsi_encuesta_satisfaccion_field_pregunta_02b>0 AND
					$encuesta->tsi_encuesta_satisfaccion_field_pregunta_02c>0 AND
					$encuesta->tsi_encuesta_satisfaccion_field_pregunta_02d>0 AND
					$encuesta->tsi_encuesta_satisfaccion_field_pregunta_02e>0 AND
					$encuesta->tsi_encuesta_satisfaccion_field_pregunta_02f>0 AND
					$encuesta->tsi_encuesta_satisfaccion_field_pregunta_04c>0 AND
					$encuesta->tsi_encuesta_satisfaccion_field_pregunta_04d>0 AND
					$encuesta->tsi_encuesta_satisfaccion_field_pregunta_07b>0
				)
			)
			{
				if($encuesta->tsi_encuesta_satisfaccion_field_pregunta_02b>0)
					$indice_interpersonal+=($encuesta->tsi_encuesta_satisfaccion_field_pregunta_02b-1)*(0.6*25);
				if($encuesta->tsi_encuesta_satisfaccion_field_pregunta_02c>0)
					$indice_interpersonal+=($encuesta->tsi_encuesta_satisfaccion_field_pregunta_02c-1)*(0.7*25);
				if($encuesta->tsi_encuesta_satisfaccion_field_pregunta_02d>0)
					$indice_interpersonal+=($encuesta->tsi_encuesta_satisfaccion_field_pregunta_02d-1)*(0.7*25);
				if($encuesta->tsi_encuesta_satisfaccion_field_pregunta_02e>0)
					$indice_interpersonal+=($encuesta->tsi_encuesta_satisfaccion_field_pregunta_02e-1)*(0.65*25);
				if($encuesta->tsi_encuesta_satisfaccion_field_pregunta_02f>0)
					$indice_interpersonal+=($encuesta->tsi_encuesta_satisfaccion_field_pregunta_02f-1)*(0.65*25);
				if($encuesta->tsi_encuesta_satisfaccion_field_pregunta_04c>0)
					$indice_interpersonal+=($encuesta->tsi_encuesta_satisfaccion_field_pregunta_04c-1)*(0.5*25);
				if($encuesta->tsi_encuesta_satisfaccion_field_pregunta_04d>0)
					$indice_interpersonal+=($encuesta->tsi_encuesta_satisfaccion_field_pregunta_04d-1)*(0.5*25);
				if($encuesta->tsi_encuesta_satisfaccion_field_pregunta_07b>0)
					$indice_interpersonal+=($encuesta->tsi_encuesta_satisfaccion_field_pregunta_07b-1)*(0.7*25);
			}
				
			$indice_interpersonal = round(($indice_interpersonal/500)*100,2);
			
			//indice interpresonal....
			
			//-----------------------------------------------------------------------------------------------
			//indice de calidad
			/*
			
			
			*/
			if
			( 
				1==1 OR
				(
					$encuesta->tsi_encuesta_satisfaccion_field_pregunta_05>0 AND
					$encuesta->tsi_encuesta_satisfaccion_field_pregunta_06>0 AND
					$encuesta->tsi_encuesta_satisfaccion_field_pregunta_07a>0 AND
					$encuesta->tsi_encuesta_satisfaccion_field_pregunta_07c>0
				)
			)
			{
				
				if($encuesta->tsi_encuesta_satisfaccion_field_pregunta_05>0)
					$indice_calidad+=(($encuesta->tsi_encuesta_satisfaccion_field_pregunta_05-1) * 25) * 0.2; 
				
				if($encuesta->tsi_encuesta_satisfaccion_field_pregunta_06==2)
					$indice_calidad+=50 ;
				if($encuesta->tsi_encuesta_satisfaccion_field_pregunta_07a>0)
					$indice_calidad+= (($encuesta->tsi_encuesta_satisfaccion_field_pregunta_07a-1) * 25) * 0.14;
				if($encuesta->tsi_encuesta_satisfaccion_field_pregunta_07c>0)
					$indice_calidad+= (($encuesta->tsi_encuesta_satisfaccion_field_pregunta_07c-1) * 25) * 0.16;
			}
			
			
			$indice_calidad = round($indice_calidad,2);
			
			//-----------------------------------------------------------------------------------------------
			
			$encuesta->tsi_encuesta_satisfaccion_field_indice_capacidad = $indice_capacidad;
			$encuesta->tsi_encuesta_satisfaccion_field_indice_interpersonal = $indice_interpersonal;
			$encuesta->tsi_encuesta_satisfaccion_field_indice_calidad = $indice_calidad;
			
			
			
			$encuesta->save();
			
			unset($encuesta);
			
		
		
		
			
			
			
			RETURN TRUE;
		}
		RETURN FALSE;
	}	
	
	
	
}