<?php

/**
 * Tsi_Encuesta_Seguimiento_Estado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Tsi_Encuesta_Seguimiento_Estado.php 97 2012-08-01 21:57:04Z mprado $
 */
class Tsi_Encuesta_Seguimiento_Estado extends BaseTsi_Encuesta_Seguimiento_Estado
{
    public function setUp() { 
		
		
	$this->hasMany('Tsi_Encuesta_Seguimiento', array(
            'local' => 'id',
            'foreign' => 'tsi_encuesta_seguimiento_estado_id'
            ));
		
	$this->actAs('Timestampable');		
		
    }

    public function get_all()
    {

        $query = Doctrine_Query::create();
        $query->from(get_class($this) . ' TSI_ENCUESTA_SEGUIMIENTO_ESTADO ');

        $query->where("1 = 1");
        return $query;
    }
}