<?php

/**
 * Tsi_Motivo_Reparacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Tsi_Motivo_Reparacion.php 97 2012-08-01 21:57:04Z mprado $
 */
class Tsi_Motivo_Reparacion extends BaseTsi_Motivo_Reparacion
{
    public function setUp() {
		
	$this->actAs('Timestampable');
	$this->actAs('SoftDelete');
		
	$this->hasOne('Tsi', array(
            'local' => 'id',
            'foreign' => 'tsi_motivo_reparacion_id'
        ));
    }
	
    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this));
        $query->where("1 = 1");
        return $query;
    }
}