<?php

/**
 * Unidad_Color_Interior
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Unidad_Color_Interior.php 97 2012-08-01 21:57:04Z mprado $
 */
class Unidad_Color_Interior extends BaseUnidad_Color_Interior
{
    public function setUp() { 
	
        $this->actAs('Timestampable');
	
		
	$this->hasMany('Unidad', array(
            'local' => 'id',
            'foreign' => 'unidad_color_interior_id',
            ));
		
    }	

    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this));
        $query->where("1 = 1");
        return $query;
    }
}