<?php

/**
 * Unidad_Estado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Unidad_Estado.php 152 2012-08-16 14:37:31Z mprado $
 */
class Unidad_Estado extends BaseUnidad_Estado
{
    public function setUp() {
		
		$this->actAs('Timestampable');
		$this->actAs('SoftDelete');
		
		$this->hasMany('Unidad', array(
            'local' => 'id',
            'foreign' => 'unidad_estado_id',
            )
        );
	}
	
	public function get_all()
	{
		$query = Doctrine_Query::create();
		$query->from(get_class($this));
		$query->where("1 = 1");
		return $query;
	}
}