<?php

/**
 * Unidad_Estado_Garantia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Unidad_Estado_Garantia.php 97 2012-08-01 21:57:04Z mprado $
 */
class Unidad_Estado_Garantia extends BaseUnidad_Estado_Garantia
{
    public function setUp() {
		
	$this->actAs('Timestampable');
		
	$this->hasMany('Unidad', array(
            'local' => 'id',
            'foreign' => 'unidad_estado_garantia_id',
            ));
    }
    
    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this));
        $query->where("1 = 1");
        return $query;
    }
}