<?php

/**
 * Upload_File_Adjunto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Upload_File_Adjunto.php 98 2012-08-02 19:31:55Z mprado $
 */
class Upload_File_Adjunto extends BaseUpload_File_Adjunto
{
    public function setUp() {
	
	$this->actAs('Timestampable');
		
	$this->hasOne('Upload_File', array(
            'local' => 'upload_file_id',
            'foreign' => 'id'
            ));		
    }

    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this));
        $query->where("1 = 1");		
        return $query;
    }

}