<?php

/**
 * Upload_File
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Upload_File.php 98 2012-08-02 19:31:55Z mprado $
 */
class Upload_File extends BaseUpload_File
{
    public function setUp() {

        $this->actAs('Timestampable');

        $this->hasMany('Upload_File_Adjunto', array(
            'local' => 'id',
            'foreign' => 'upload_file_id',
            ));
            
        $this->hasOne('Admin', array(
            'local' => 'admin_id',
            'foreign' => 'id',
            ));
    }


    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this) .' UPLOAD_FILE ');
        $query->where("1 = 1");
        $query->leftJoin('UPLOAD_FILE.Upload_File_Adjunto UPLOAD_FILE_ADJUNTO');		
        return $query;
    }
}