<?php

/**
 * Usado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Usado.php 97 2012-08-01 21:57:04Z mprado $
 */
class Usado extends BaseUsado
{
    public function setUp() {
	
        $this->actAs('Timestampable');
	$this->actAs('SoftDelete');

	$this->hasOne('Auto_Version', array(
            'local' => 'auto_version_id',
            'foreign' => 'id'
            ));
	
        $this->hasOne('Unidad', array(
            'local' => 'unidad_id',
            'foreign' => 'id'
            ));
	
        $this->hasOne('Unidad as Unidad_Entregada', array(
            'local' => 'unidad_entregada_id',
            'foreign' => 'id'
            ));
	
        $this->hasOne('Auto_Anio', array(
            'local' => 'auto_anio_id',
            'foreign' => 'id'
            ));
		
        $this->hasOne('Sucursal', array(
            'local' => 'sucursal_id',
            'foreign' => 'id'
            ));
		
        $this->hasOne('Usado_Tipo_Venta', array(
            'local' => 'usado_tipo_venta_id',
            'foreign' => 'id'
            ));
		
        $this->hasOne('Usado_Tipo_Ingreso', array(
            'local' => 'usado_tipo_ingreso_id',
            'foreign' => 'id'
            ));
		
        $this->hasOne('Moneda as Moneda_Toma', array(
            'local' => 'moneda_precio_toma_id',
            'foreign' => 'id'
            ));
		
        $this->hasOne('Moneda as Moneda_Venta', array(
            'local' => 'moneda_precio_venta_id',
            'foreign' => 'id'
            ));
		
        $this->hasOne('Auto_Color', array(
            'local' => 'auto_color_id',
            'foreign' => 'id'
            ));
		
        $this->hasOne('Backend_Estado', array(
            'local' => 'backend_estado_id',
            'foreign' => 'id'
            ));
		
        $this->hasOne('Admin as Admin_Alta', array(
            'local' => 'usado_field_admin_alta_id',
            'foreign' => 'id'
            ));
		
        $this->hasOne('Admin as Admin_Modifica', array(
            'local' => 'usado_field_admin_modifica_id',
            'foreign' => 'id'
            ));
		
        $this->hasMany('Usado_Imagen', array(
            'local' => 'id',
            'foreign' => 'usado_id',
            ));
    }

    public function get_all()
    {

        $query = Doctrine_Query::create();
        $query->from(get_class($this) . ' USADO ');
        $query->where("1 = 1");

        $query->leftJoin('USADO.Auto_Version USADO_AUTO_VERSION');
        $query->leftJoin('USADO_AUTO_VERSION.Auto_Modelo USADO_AUTO_MODELO');
        $query->leftJoin('USADO_AUTO_MODELO.Auto_Marca USADO_AUTO_MARCA');

        $query->leftJoin('USADO.Unidad USADO_UNIDAD');
        $query->leftJoin('USADO.Unidad_Entregada UNIDAD_ENTREGADA');
        $query->leftJoin('USADO.Auto_Anio AUTO_ANIO ');
        $query->leftJoin('USADO.Sucursal SUCURSAL ');
        $query->leftJoin('USADO.Usado_Tipo_Venta USADO_TIPO_VENTA ');
        $query->leftJoin('USADO.Usado_Tipo_Ingreso USADO_TIPO_INGRESO ');
        $query->leftJoin('USADO.Moneda_Toma MONEDA_TOMA ');
        $query->leftJoin('USADO.Moneda_Venta MONEDA_VENTA ');
        $query->leftJoin('USADO.Auto_Color AUTO_COLOR ');
        $query->leftJoin('USADO.Backend_Estado BACKEND_ESTADO');
        $query->leftJoin('USADO.Admin_Alta ADMIN_ALTA ');
        $query->leftJoin('USADO.Admin_Modifica ADMIN_MODIFICA ');
        return $query;
    }
}