<?php

/**
 * Usado_Tipo_Venta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Usado_Tipo_Venta.php 98 2012-08-02 19:31:55Z mprado $
 */
class Usado_Tipo_Venta extends BaseUsado_Tipo_Venta
{
    public function setUp() {
		
	$this->actAs('Timestampable');
	$this->actAs('SoftDelete');
		
	$this->hasMany('Usado', array(
            'local' => 'id',
            'foreign' => 'usado_tipo_venta_id',
            ));
    }

    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this));
        $query->where("1 = 1");
        return $query;
    }
}