<?php

/**
 * Vin_Procedencia_Ktype
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Vin_Procedencia_Ktype.php 97 2012-08-01 21:57:04Z mprado $
 */
class Vin_Procedencia_Ktype extends BaseVin_Procedencia_Ktype
{
    public function setUp() {

        $this->actAs('Timestampable');
        $this->actAs('SoftDelete');

        $this->hasMany('Unidad', array(
            'local' => 'id',
            'foreign' => 'vin_procedencia_htype_id'
            ));
    }

    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this));
        $query->where("1 = 1");
        return $query;
    }
}