<?php

/**
 * Vin_Modelo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Vin_Modelo.php 97 2012-08-01 21:57:04Z mprado $
 */
class Vin_Modelo extends BaseVin_Modelo
{
    public function setUp() {
		
	$this->actAs('Timestampable');
	$this->actAs('SoftDelete');
		
	$this->hasOne('Auto_Modelo', array(
            'local' => 'auto_modelo_id',
            'foreign' => 'id'
        ));
		
	$this->hasMany('Vin_Version', array(
            'local' => 'id',
            'foreign' => 'vin_modelo_id'
        ));
    }
	
    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this) . ' V ');
        $query->where("1 = 1");

        $query->leftJoin('V.Auto_Modelo AM ');
        return $query;
    }
}