<?php

/**
 * Vin_Version
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Vin_Version.php 97 2012-08-01 21:57:04Z mprado $
 */
class Vin_Version extends BaseVin_Version
{
    public function setUp() {
		
	$this->actAs('Timestampable');
	$this->actAs('SoftDelete');
		
	$this->hasOne('Vin_Modelo', array(
                'local' => 'vin_modelo_id',
                'foreign' => 'id'
                ));
		
	$this->hasOne('Auto_Version', array(
                'local' => 'auto_version_id',
                'foreign' => 'id'
                ));
    }
    
    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this) . ' V ' );
        $query->where("1 = 1");

        $query->leftJoin('V.Vin_Modelo M ');
        $query->leftJoin('V.Auto_Version AV ');
        $query->leftJoin('AV.Auto_Modelo AM ');

        return $query;
    }
}