<?php

/**
 * Vin_Anio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Vin_Anio.php 97 2012-08-01 21:57:04Z mprado $
 */
class Vin_Anio extends BaseVin_Anio
{
    public function setUp() {
		
        $this->actAs('Timestampable');
        $this->actAs('SoftDelete');
        $this->hasOne('Auto_Anio', array(
            'local' => 'auto_anio_id',
            'foreign' => 'id'
        ));
    }

    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this) . ' A ');
        $query->where("1 = 1");

        $query->leftJoin('A.Auto_Anio AM ');
        return $query;
    }
}