<?php

/**
 * Vin_Puerta_Transmision
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Honda_HARWS
 * @subpackage Doctrine
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Vin_Puerta_Transmision.php 97 2012-08-01 21:57:04Z mprado $
 */
class Vin_Puerta_Transmision extends BaseVin_Puerta_Transmision
{
    public function setUp() {
		
	$this->actAs('Timestampable');
	$this->actAs('SoftDelete');
		
	$this->hasOne('Auto_Puerta_Cantidad', array(
            'local' => 'auto_puerta_cantidad_id',
            'foreign' => 'id',
            ));
		
        $this->hasOne('Auto_Transmision', array(
            'local' => 'auto_transmision_id',
            'foreign' => 'id',
            ));
    }

    public function get_all()
    {
        $query = Doctrine_Query::create();
        $query->from(get_class($this) . ' P ');
        $query->where("1 = 1");

        $query->leftJoin('P.Auto_Puerta_Cantidad C ');
        $query->leftJoin('P.Auto_Transmision T ');

        return $query;
    }
}